import type { PictureSource } from './picture';
import { BLUE, CYAN, DARK, GREEN, MAGENTA, ORANGE, PURPLE, RED, SLATE, TAN, WHITE, YELLOW } from './palette';

/**
 * The picture library.
 *
 * A level is a picture, a setting and a seed — nothing else — so this is
 * the only place artwork lives, and the generator builds every level in
 * the campaign out of it. Adding a picture here adds one level per
 * setting, so the campaign grows five at a time.
 *
 * Ordered smallest first, which is the order the campaign sweeps them in:
 * inside a run of a hundred the artwork grows, and the setting turns the
 * pressure up between runs.
 *
 * Every picture is drawn with an outline, because the outline is what
 * makes the level a puzzle — it seals its own fill in, so the order the
 * picture opens up in is the thing the player is actually solving.
 *
 * Three rules `levels.test.ts` checks rather than trusting: every row of a
 * picture is the same width, no two colors in one picture sit closer than
 * the distance rule allows (which is what keeps `red` and `tan` — 142
 * apart — off the same artwork), and every name is unique.
 */
export interface LibraryPicture extends PictureSource {
  name: string;
}

export const PICTURES: readonly LibraryPicture[] = [
  {
    name: 'Heart',
    // 8x7, 40 tiles, 2 colors
    rows: [
      '.DD..DD.',
      'DRRDDRRD',
      'DRRRRRRD',
      'DRRRRRRD',
      '.DRRRRD.',
      '..DRRD..',
      '...DD...',
    ],
    legend: { R: RED, D: DARK },
  },
  {
    name: 'Star',
    // 9x9, 43 tiles, 2 colors
    rows: [
      '....D....',
      '...DYD...',
      '...DYD...',
      'DDDDYDDDD',
      '.DYYYYYD.',
      '..DYYYD..',
      '.DYYDYYD.',
      'DYD...DYD',
      'D.......D',
    ],
    legend: { Y: YELLOW, D: DARK },
  },
  {
    name: 'Chick',
    // 9x9, 59 tiles, 3 colors
    rows: [
      '...DDD...',
      '..DYYYD..',
      '.DYDYDYD.',
      '.DYYOYYD.',
      '.DYYYYYD.',
      'DDYYYYYDD',
      'DYYYYYYYD',
      '.DYYYYYD.',
      '..DDDDD..',
    ],
    legend: { Y: YELLOW, O: ORANGE, D: DARK },
  },
  {
    name: 'Duck',
    // 12x9, 60 tiles, 3 colors
    rows: [
      '....DDD.....',
      '...DWWWD....',
      '..DWDWWD....',
      '.DOOWWWD....',
      '..DDDWWDDD..',
      '...DWWWWWWD.',
      '..DWWWWWWWD.',
      '..DWWWWWWD..',
      '...DDDDDD...',
    ],
    legend: { O: ORANGE, W: WHITE, D: DARK },
  },
  {
    name: 'Banana',
    // 11x10, 61 tiles, 2 colors
    rows: [
      '.......DDD.',
      '......DDYD.',
      '.....DDYYD.',
      'DD..DDYYYD.',
      'DYDDYYYYD..',
      'DYYYYYYYD..',
      '.DYYYYYYD..',
      '.DYYYYYD...',
      '..DYYYD....',
      '...DDD.....',
    ],
    legend: { Y: YELLOW, D: DARK },
  },
  {
    name: 'Lightning',
    // 9x14, 62 tiles, 2 colors
    rows: [
      '.....DD..',
      '....DYD..',
      '...DYYD..',
      '..DYYYD..',
      '..DYYD...',
      '.DYYYD...',
      '.DYDDDDD.',
      'DYYYYYYD.',
      'DDDDDYYD.',
      '....DYYD.',
      '...DYYD..',
      '...DYD...',
      '..DYD....',
      '..DD.....',
    ],
    legend: { Y: YELLOW, D: DARK },
  },
  {
    name: 'Snake',
    // 13x12, 65 tiles, 2 colors
    rows: [
      '....DDDDD....',
      '...DGGGGGD...',
      '..DGDGGGDGD..',
      '..DGGGGGGGD..',
      '...DGGGGGD...',
      '....DGGGD....',
      '...DGGGD.....',
      '..DGGGD......',
      '..DGGD.......',
      '.DGGD........',
      '.DGD.........',
      '.DD..........',
    ],
    legend: { G: GREEN, D: DARK },
  },
  {
    name: 'Candle',
    // 9x14, 66 tiles, 3 colors
    rows: [
      '....D....',
      '...DYD...',
      '...DYD...',
      '..DYYYD..',
      '..DYYYD..',
      '...DYD...',
      '....D....',
      '..DDDDD..',
      '.DWWWWWD.',
      '.DWWWWWD.',
      '.DWWWWWD.',
      '.DWWWWWD.',
      '.DWWWWWD.',
      '..DDDDD..',
    ],
    legend: { Y: YELLOW, W: WHITE, D: DARK },
  },
  {
    name: 'Key',
    // 13x9, 68 tiles, 2 colors
    rows: [
      '..DDDD.......',
      '.DYYYYD......',
      'DYYDDYYDDDDD.',
      'DYD..DYYYYYYD',
      'DYD..DYDDDYDD',
      'DYYDDYYDDDYD.',
      '.DYYYYD...DD.',
      '..DDDD.......',
      '.............',
    ],
    legend: { Y: YELLOW, D: DARK },
  },
  {
    name: 'Kite',
    // 11x14, 68 tiles, 3 colors
    rows: [
      '....DD.....',
      '...DMYD....',
      '..DMMYYD...',
      '.DMMMYYYD..',
      'DMMMMYYYYD.',
      'DMMMMYYYYD.',
      '.DMMMYYYD..',
      '..DMMYYD...',
      '...DMYD....',
      '....DD.....',
      '....DD.....',
      '...DD......',
      '....DD.....',
      '...DD......',
    ],
    legend: { Y: YELLOW, M: MAGENTA, D: DARK },
  },
  {
    name: 'Carrot',
    // 9x14, 69 tiles, 3 colors
    rows: [
      '.DD...DD.',
      'DGGD.DGGD',
      'DGGGDGGGD',
      '.DGGDGGD.',
      '..DDGDD..',
      '..DOOOD..',
      '..DOOOD..',
      '..DOOOD..',
      '..DOOOD..',
      '...DOOD..',
      '...DOOD..',
      '...DOD...',
      '...DOD...',
      '....DD...',
    ],
    legend: { G: GREEN, O: ORANGE, D: DARK },
  },
  {
    name: 'Flower',
    // 13x13, 71 tiles, 4 colors
    rows: [
      '....DDD......',
      '...DMMMD.....',
      '..DMMMMMD....',
      '.DMMMYMMMD...',
      '.DMMYYYMMD...',
      '..DMMYMMD....',
      '...DMMMD.....',
      '....DGD......',
      '...DGGGD.....',
      '..DGDGDGD....',
      '.DGD.G.DGD...',
      '.....G.......',
      '....DDD......',
    ],
    legend: { Y: YELLOW, G: GREEN, M: MAGENTA, D: DARK },
  },
  {
    name: 'Bat',
    // 14x8, 72 tiles, 2 colors
    rows: [
      '.D..........D.',
      'DPD...DD...DPD',
      'DPPD.DPPD.DPPD',
      'DPPPDDPPDDPPPD',
      'DPPPPPPPPPPPPD',
      '.DPPPDPPDPPPD.',
      '..DPD.DD.DPD..',
      '...D.......D..',
    ],
    legend: { P: PURPLE, D: DARK },
  },
  {
    name: 'Raindrop',
    // 9x13, 73 tiles, 2 colors
    rows: [
      '....D....',
      '...DCD...',
      '...DCD...',
      '..DCCCD..',
      '..DCCCD..',
      '.DCCCCCD.',
      '.DCCCCCD.',
      'DCCCCCCCD',
      'DCCCCCCCD',
      'DCCCCCCCD',
      '.DCCCCCD.',
      '..DCCCD..',
      '...DDD...',
    ],
    legend: { C: CYAN, D: DARK },
  },
  {
    name: 'Lemon',
    // 12x9, 74 tiles, 3 colors
    rows: [
      '.....DDD....',
      '....DGGGD...',
      '..DDDDDDDD..',
      '.DYYYYYYYYD.',
      'DYYYYYYYYYYD',
      'DYYYYYYYYYYD',
      '.DYYYYYYYYD.',
      '..DYYYYYYD..',
      '...DDDDDD...',
    ],
    legend: { Y: YELLOW, G: GREEN, D: DARK },
  },
  {
    name: 'Diamond',
    // 11x11, 75 tiles, 2 colors
    rows: [
      '..DDDDDDD..',
      '.DCCCDCCCD.',
      'DCCCCDCCCCD',
      'DDDDDDDDDDD',
      '.DCCCCCCCD.',
      '..DCCCCCD..',
      '..DCCCCCD..',
      '...DCCCD...',
      '...DCCCD...',
      '....DCD....',
      '.....D.....',
    ],
    legend: { C: CYAN, D: DARK },
  },
  {
    name: 'Moon',
    // 11x13, 75 tiles, 2 colors
    rows: [
      '...DDDD....',
      '..DYYYYD...',
      '.DYYYYDD...',
      'DYYYYDD....',
      'DYYYDD.....',
      'DYYYD......',
      'DYYYD......',
      'DYYYD......',
      'DYYYDD.....',
      'DYYYYDD....',
      '.DYYYYDD...',
      '..DYYYYD...',
      '...DDDD....',
    ],
    legend: { Y: YELLOW, D: DARK },
  },
  {
    name: 'Deer',
    // 12x12, 76 tiles, 3 colors
    rows: [
      'D.D......D.D',
      'DD.D....D.DD',
      '.DDD....DDD.',
      '..DDD..DDD..',
      '...DDDDDD...',
      '...DTTTTD...',
      '..DTTTTTTD..',
      '..DTDTTDTD..',
      '..DTTTTTTD..',
      '..DTTWWTTD..',
      '...DTTTTD...',
      '....DDDD....',
    ],
    legend: { W: WHITE, D: DARK, T: TAN },
  },
  {
    name: 'Balloon',
    // 10x14, 77 tiles, 3 colors
    rows: [
      '...DDDD...',
      '..DMMMMD..',
      '.DMMMMMMD.',
      'DMMMWMMMMD',
      'DMMMWMMMMD',
      'DMMMMMMMMD',
      '.DMMMMMMD.',
      '..DMMMMD..',
      '...DMMD...',
      '....DD....',
      '....DD....',
      '...DDD....',
      '....DD....',
      '....DD....',
    ],
    legend: { M: MAGENTA, W: WHITE, D: DARK },
  },
  {
    name: 'Apple',
    // 10x11, 78 tiles, 4 colors
    rows: [
      '.....DD...',
      '....DGGD..',
      '..DDDRDD..',
      '.DRRRRRRD.',
      'DRRWRRRRRD',
      'DRRWRRRRRD',
      'DRRRRRRRRD',
      'DRRRRRRRRD',
      '.DRRRRRRD.',
      '..DRRRRD..',
      '...DDDD...',
    ],
    legend: { R: RED, G: GREEN, W: WHITE, D: DARK },
  },
  {
    name: 'Mouse',
    // 11x9, 80 tiles, 3 colors
    rows: [
      '.DD.....DD.',
      'DMMD...DMMD',
      'DMMMD.DMMMD',
      '.DSSDDDSSD.',
      'DSSSSSSSSSD',
      'DSDSSSSSDSD',
      'DSSSSMSSSSD',
      '.DSSSSSSSD.',
      '..DDDDDDD..',
    ],
    legend: { M: MAGENTA, D: DARK, S: SLATE },
  },
  {
    name: 'Parrot',
    // 10x13, 80 tiles, 4 colors
    rows: [
      '...DDDD...',
      '..DYYYYD..',
      '.DYDYYYYD.',
      'DODYYYYYD.',
      'DOODYYYYD.',
      '.DODGGGGD.',
      '..DDGGGGD.',
      '...DGGGGD.',
      '...DGGGGD.',
      '...DGGGGD.',
      '...DGGGD..',
      '...DGGD...',
      '....DD....',
    ],
    legend: { Y: YELLOW, G: GREEN, O: ORANGE, D: DARK },
  },
  {
    name: 'Pine',
    // 11x14, 80 tiles, 3 colors
    rows: [
      '....DD.....',
      '...DGGD....',
      '...DGGD....',
      '..DGGGGD...',
      '..DGGGGD...',
      '.DGGGGGGD..',
      '.DGGGGGGD..',
      'DGGGGGGGGD.',
      'DGGGGGGGGD.',
      '.DDDDDDDD..',
      '....DTD....',
      '....DTD....',
      '....DTD....',
      '...DDDDD...',
    ],
    legend: { G: GREEN, D: DARK, T: TAN },
  },
  {
    name: 'Lolly',
    // 10x14, 81 tiles, 4 colors
    rows: [
      '...DDDD...',
      '..DMWMMD..',
      '.DMWMWMMD.',
      'DMWMMMWMMD',
      'DMMWMMMWMD',
      'DMMMWMMMWD',
      '.DMMMWMMD.',
      '..DMMMWD..',
      '...DDDD...',
      '....DTD...',
      '....DTD...',
      '....DTD...',
      '....DTD...',
      '....DDD...',
    ],
    legend: { M: MAGENTA, W: WHITE, D: DARK, T: TAN },
  },
  {
    name: 'Bell',
    // 11x12, 82 tiles, 2 colors
    rows: [
      '....DD.....',
      '...DDDD....',
      '..DYYYYD...',
      '.DYYYYYYD..',
      '.DYYYYYYD..',
      'DYYYYYYYYD.',
      'DYYYYYYYYD.',
      'DYYYYYYYYD.',
      'DDDDDDDDDD.',
      '.DDYYYYDD..',
      '...DYYD....',
      '....DD.....',
    ],
    legend: { Y: YELLOW, D: DARK },
  },
  {
    name: 'Cactus',
    // 11x14, 82 tiles, 3 colors
    rows: [
      '....DDD....',
      '...DMMMD...',
      '....DDD....',
      '....DGD....',
      '.DD.DGD.DD.',
      'DGD.DGD.DGD',
      'DGDDDGDDDGD',
      'DGGGDGDGGGD',
      '.DDDDGDDDD.',
      '....DGD....',
      '....DGD....',
      '...DGGGD...',
      '...DGGGD...',
      '...DDDDD...',
    ],
    legend: { G: GREEN, M: MAGENTA, D: DARK },
  },
  {
    name: 'Hedgehog',
    // 14x8, 82 tiles, 3 colors
    rows: [
      '...D.D.D.D....',
      '..DDDDDDDDD...',
      '.DDTTTTTTTDD..',
      'DDTTTTTTTTTDD.',
      'DTTTTTTTTTWWWD',
      '.DTTTTTTTWWDDD',
      '..DTTTTTTDWD..',
      '...DDDDDDDD...',
    ],
    legend: { W: WHITE, D: DARK, T: TAN },
  },
  {
    name: 'Tree',
    // 11x13, 83 tiles, 3 colors
    rows: [
      '....DDD....',
      '...DGGGD...',
      '..DGGGGGD..',
      '.DGGGGGGGD.',
      'DGGGGGGGGGD',
      '.DGGGGGGGD.',
      '..DGGGGGD..',
      '.DGGGGGGGD.',
      '..DGGGGGD..',
      '...DDTDD...',
      '....DTD....',
      '....DTD....',
      '...DDDDD...',
    ],
    legend: { G: GREEN, D: DARK, T: TAN },
  },
  {
    name: 'Boat',
    // 15x11, 84 tiles, 3 colors
    rows: [
      '......DD.......',
      '......DWD......',
      '......DWWD.....',
      '......DWWWD....',
      '......DWWWWD...',
      '......DDDDDD...',
      'DDDDDDDDDDDDDD.',
      'DWWWWWWWWWWWWD.',
      '.DWWWWWWWWWWD..',
      '..DDDDDDDDDD...',
      '...DCCCCCCD....',
    ],
    legend: { C: CYAN, W: WHITE, D: DARK },
  },
  {
    name: 'Cloud',
    // 14x8, 84 tiles, 3 colors
    rows: [
      '.....DDDD.....',
      '...DDWWWWDD...',
      '..DWWWWWWWWD..',
      '.DWWWWWWWWWWD.',
      'DWWWWWWWWWWWWD',
      'DWWWWWWWWWWWWD',
      '.DSSSSSSSSSSD.',
      '..DDDDDDDDDD..',
    ],
    legend: { W: WHITE, D: DARK, S: SLATE },
  },
  {
    name: 'Turtle',
    // 13x9, 84 tiles, 3 colors
    rows: [
      '....DDDDD....',
      '...DGGGGGD...',
      '..DGDDDDDGD..',
      '.DGDGGGGGDGD.',
      'DYDGGDGDGGDYD',
      'DYDGGGGGGGDYD',
      '.DGDGGGGGDGD.',
      '..DDDDDDDDD..',
      '...DYD.DYD...',
    ],
    legend: { Y: YELLOW, G: GREEN, D: DARK },
  },
  {
    name: 'Candy',
    // 13x9, 85 tiles, 3 colors
    rows: [
      'DD.........DD',
      'DDD.......DDD',
      'DMDDDDDDDDDMD',
      'DMMDMMMMMDMMD',
      'DMMDMWWWMDMMD',
      'DMMDMMMMMDMMD',
      'DMDDDDDDDDDMD',
      'DDD.......DDD',
      'DD.........DD',
    ],
    legend: { M: MAGENTA, W: WHITE, D: DARK },
  },
  {
    name: 'Grapes',
    // 11x14, 85 tiles, 3 colors
    rows: [
      '......DDD..',
      '.....DGGD..',
      '...DDDGD...',
      '..DGGDDD...',
      '..DDDDD....',
      '.DDDDDDDD..',
      'DPPPPPPPPD.',
      'DPDPPDPPPD.',
      '.DPPPPPPD..',
      '.DPDPPDPD..',
      '..DPPPPD...',
      '..DPPPPD...',
      '...DPPD....',
      '....DD.....',
    ],
    legend: { G: GREEN, P: PURPLE, D: DARK },
  },
  {
    name: 'Leaf',
    // 11x13, 86 tiles, 3 colors
    rows: [
      '.......DDD.',
      '.....DDGGD.',
      '...DDGGGGD.',
      '..DGGGDGGD.',
      '.DGGGDGGGD.',
      '.DGGDGGGGD.',
      'DGGDGGGGGD.',
      'DGDGGGGGGD.',
      'DGDGGGGGD..',
      '.DDGGGGD...',
      '...DDDD....',
      '....DTD....',
      '....DD.....',
    ],
    legend: { G: GREEN, D: DARK, T: TAN },
  },
  {
    name: 'Shell',
    // 12x10, 86 tiles, 3 colors
    rows: [
      '.....DD.....',
      '...DDMMDD...',
      '..DMMMMMMD..',
      '.DMDMMMMDMD.',
      'DMDMDMMDMDMD',
      'DMDMDMMDMDMD',
      'DMMMMMMMMMMD',
      '.DMMMMMMMMD.',
      '..DWWWWWWD..',
      '...DDDDDD...',
    ],
    legend: { M: MAGENTA, W: WHITE, D: DARK },
  },
  {
    name: 'Guitar',
    // 11x14, 88 tiles, 2 colors
    rows: [
      '....DDD....',
      '....DTD....',
      '....DTD....',
      '....DTD....',
      '....DTD....',
      '....DTD....',
      '...DDTDD...',
      '..DTTTTTD..',
      '.DTTDDDTTD.',
      'DTTTDDDTTTD',
      'DTTTTDTTTTD',
      'DTTTTTTTTTD',
      '.DTTTTTTTD.',
      '..DDDDDDD..',
    ],
    legend: { D: DARK, T: TAN },
  },
  {
    name: 'Mountain',
    // 14x10, 88 tiles, 3 colors
    rows: [
      '......DD......',
      '.....DWWD.....',
      '....DWWWWD....',
      '...DWDDDWWD...',
      '..DSDD..DDWD..',
      '..DSSD...DSD..',
      '.DSSSSD.DSSSD.',
      'DSSSSSSDSSSSSD',
      'DSSSSSSSSSSSSD',
      'DDDDDDDDDDDDDD',
    ],
    legend: { W: WHITE, D: DARK, S: SLATE },
  },
  {
    name: 'Fried egg',
    // 11x10, 89 tiles, 3 colors
    rows: [
      '....DDDD...',
      '..DDWWWWDD.',
      '.DWWWWWWWWD',
      'DWWWDDDWWWD',
      'DWWDYYYDWWD',
      'DWWDYYYDWWD',
      'DWWWDDDWWWD',
      '.DWWWWWWWWD',
      '..DWWWWWDD.',
      '...DDDDD...',
    ],
    legend: { Y: YELLOW, W: WHITE, D: DARK },
  },
  {
    name: 'Pear',
    // 11x14, 89 tiles, 3 colors
    rows: [
      '....DD.....',
      '....DTD....',
      '...DDTDD...',
      '..DGGDGGD..',
      '...DDDDD...',
      '....DGD....',
      '...DGGGD...',
      '...DGGGD...',
      '..DGGGGGD..',
      '.DGGGGGGGD.',
      'DGGGGGGGGGD',
      'DGGGGGGGGGD',
      '.DGGGGGGGD.',
      '..DDDDDDD..',
    ],
    legend: { G: GREEN, D: DARK, T: TAN },
  },
  {
    name: 'Tomato',
    // 11x12, 89 tiles, 3 colors
    rows: [
      '....DD.....',
      '...DGD.....',
      '..DDGDDD...',
      '.DGGGGGGD..',
      '..DDDDDDD..',
      '.DRRRRRRRD.',
      'DRRRRRRRRRD',
      'DRRRRRRRRRD',
      'DRRRRRRRRRD',
      '.DRRRRRRRD.',
      '..DRRRRRD..',
      '...DDDDD...',
    ],
    legend: { R: RED, G: GREEN, D: DARK },
  },
  {
    name: 'Bulb',
    // 11x13, 90 tiles, 3 colors
    rows: [
      '...DDDD....',
      '..DYYYYD...',
      '.DYYYYYYD..',
      'DYYYYYYYYD.',
      'DYYYYYYYYD.',
      'DYYYYYYYYD.',
      '.DYYYYYYD..',
      '..DYYYYD...',
      '..DSSSSD...',
      '..DDDDDD...',
      '..DSSSSD...',
      '..DDDDDD...',
      '...DSSD....',
    ],
    legend: { Y: YELLOW, D: DARK, S: SLATE },
  },
  {
    name: 'Ladybird',
    // 11x10, 90 tiles, 2 colors
    rows: [
      '...DDDDD...',
      '..DDDDDDD..',
      '.DDDDDDDDD.',
      '.DRRRDRRRD.',
      'DRRRRDRRRRD',
      'DRDRRDRRDRD',
      'DRRRRDRRRRD',
      'DRRDRDRDRRD',
      '.DRRRDRRRD.',
      '..DDDDDDD..',
    ],
    legend: { R: RED, D: DARK },
  },
  {
    name: 'Palm',
    // 13x14, 90 tiles, 3 colors
    rows: [
      '.DD.......DD.',
      'DGGDD...DDGGD',
      '.DGGGD.DGGGD.',
      '..DGGGDGGGD..',
      '.DDDGGGGGDDD.',
      'DGGGDDGDDGGGD',
      '.DDD..DD..DDD',
      '......DTD....',
      '.....DTTD....',
      '.....DTD.....',
      '.....DTTD....',
      '....DTTD.....',
      '....DTTD.....',
      '....DDD......',
    ],
    legend: { G: GREEN, D: DARK, T: TAN },
  },
  {
    name: 'Icecream',
    // 9x14, 91 tiles, 4 colors
    rows: [
      '..DDDDD..',
      '.DMMMMMD.',
      'DMMMMMMMD',
      'DMMMMMMMD',
      '.DMMMMMD.',
      '.DWWWWWD.',
      'DWWWWWWWD',
      'DWWWWWWWD',
      '.DWWWWWD.',
      '.DTTTTTD.',
      '..DTTTD..',
      '..DTTTD..',
      '...DTD...',
      '...DD....',
    ],
    legend: { M: MAGENTA, W: WHITE, D: DARK, T: TAN },
  },
  {
    name: 'Watermelon',
    // 13x9, 91 tiles, 4 colors
    rows: [
      'DDDDDDDDDDDDD',
      'DGGGGGGGGGGGD',
      'DDWWWWWWWWWDD',
      '.DRRRRRRRRRD.',
      '.DRRDRRRDRRD.',
      '..DRRRRRRRD..',
      '..DRRDRRDRD..',
      '...DRRRRRD...',
      '....DDDDD....',
    ],
    legend: { R: RED, G: GREEN, W: WHITE, D: DARK },
  },
  {
    name: 'Cup',
    // 12x10, 93 tiles, 3 colors
    rows: [
      '.DDDDDDDDD..',
      '.DWWWWWWWD..',
      '.DWCCCCCWDD.',
      '.DWCCCCCWDWD',
      '.DWCCCCCWDWD',
      '.DWCCCCCWDDD',
      '.DWCCCCCWD..',
      '.DWCCCCCWD..',
      '..DWWWWWD...',
      '..DDDDDDD...',
    ],
    legend: { C: CYAN, W: WHITE, D: DARK },
  },
  {
    name: 'Pizza',
    // 13x11, 93 tiles, 4 colors
    rows: [
      '.....DDD.....',
      '....DTTTD....',
      '....DYYYD....',
      '...DYYGYYD...',
      '...DYYYYYD...',
      '..DYGYYYGYD..',
      '..DYYYYYYYD..',
      '.DYYGYYYGYYD.',
      '.DYYYYYYYYYD.',
      'DTTTTTTTTTTTD',
      'DDDDDDDDDDDDD',
    ],
    legend: { Y: YELLOW, G: GREEN, D: DARK, T: TAN },
  },
  {
    name: 'Bee',
    // 13x11, 94 tiles, 3 colors
    rows: [
      '.DD.......DD.',
      'DWWD.....DWWD',
      'DWWWD...DWWWD',
      '.DWWDDDDDWWD.',
      '..DDYYYYYDD..',
      '..DYYYYYYYD..',
      '..DDDDDDDDD..',
      '..DYYYYYYYD..',
      '..DDDDDDDDD..',
      '..DYYYYYYYD..',
      '...DDDDDDD...',
    ],
    legend: { Y: YELLOW, W: WHITE, D: DARK },
  },
  {
    name: 'Strawberry',
    // 11x12, 94 tiles, 4 colors
    rows: [
      '...DDDDD...',
      '..DGGGGGD..',
      '.DGDGGGDGD.',
      '..DDDDDDD..',
      '.DRRRRRRRD.',
      'DRWRRRWRRRD',
      'DRRRRRRRWRD',
      'DRRWRRRRRRD',
      '.DRRRRWRRD.',
      '..DRRRRRD..',
      '...DRRRD...',
      '....DDD....',
    ],
    legend: { R: RED, G: GREEN, W: WHITE, D: DARK },
  },
  {
    name: 'Cherry',
    // 11x14, 95 tiles, 3 colors
    rows: [
      '......DDDD.',
      '.....DGGGD.',
      '..DDDDGGD..',
      '.DGGGDGD...',
      '.DGGGGDD...',
      '..DDDDD....',
      '....DDD....',
      '..DDRRRDD..',
      '.DRRRRRRRD.',
      'DRRRRRRRRRD',
      'DRRRRRRRRRD',
      '.DRRRRRRRD.',
      '..DDRRRDD..',
      '....DDD....',
    ],
    legend: { R: RED, G: GREEN, D: DARK },
  },
  {
    name: 'Crab',
    // 13x9, 95 tiles, 2 colors
    rows: [
      '.DD.......DD.',
      'DRRD.....DRRD',
      'DRRDDDDDDDRRD',
      '.DDRRRRRRRDD.',
      'DRRRDRRRDRRRD',
      'DRRRRRRRRRRRD',
      'DRRRRRRRRRRRD',
      '.DRRRRRRRRRD.',
      '..DDDDDDDDD..',
    ],
    legend: { R: RED, D: DARK },
  },
  {
    name: 'Ghost',
    // 10x11, 95 tiles, 3 colors
    rows: [
      '...DDDD...',
      '..DWWWWD..',
      '.DWWWWWWD.',
      'DWWDWWDWWD',
      'DWWDWWDWWD',
      'DWWWWWWWWD',
      'DWWWWWWWWD',
      'DWWMMMMWWD',
      'DWWWWWWWWD',
      'DWDWWDWWDD',
      'DDD.DD.DD.',
    ],
    legend: { M: MAGENTA, W: WHITE, D: DARK },
  },
  {
    name: 'Bunny',
    // 11x12, 96 tiles, 3 colors
    rows: [
      '.DD...DD...',
      'DWWD.DWWD..',
      'DWMD.DWMD..',
      'DWMD.DWMD..',
      'DWWD.DWWD..',
      '.DWWDDWWD..',
      '.DWWWWWWD..',
      'DWWDWWDWWD.',
      'DWWWWWWWWD.',
      'DWWWMWWWWD.',
      '.DWWWWWWD..',
      '..DDDDDD...',
    ],
    legend: { M: MAGENTA, W: WHITE, D: DARK },
  },
  {
    name: 'Jellyfish',
    // 11x12, 96 tiles, 2 colors
    rows: [
      '...DDDDD...',
      '..DMMMMMD..',
      '.DMMMMMMMD.',
      'DMMMMMMMMMD',
      'DMMDMMMDMMD',
      'DMMMMMMMMMD',
      '.DMMMMMMMD.',
      '.DDDDDDDDD.',
      '.DMD.DMD...',
      '.DMD.DMD...',
      '..DMD.DMD..',
      '..DDD.DDD..',
    ],
    legend: { M: MAGENTA, D: DARK },
  },
  {
    name: 'Umbrella',
    // 13x14, 96 tiles, 3 colors
    rows: [
      '.....DDD.....',
      '..DDDMMMDDD..',
      '.DMMMMMMMMMD.',
      'DMMMMMMMMMMMD',
      'DMDMMMDMMMDMD',
      'DDDDDDDDDDDDD',
      '.DD.DD.DD.DD.',
      '......DSD....',
      '......DSD....',
      '......DSD....',
      '......DSDD...',
      '.....DSSSD...',
      '.....DSDDD...',
      '.....DDD.....',
    ],
    legend: { M: MAGENTA, D: DARK, S: SLATE },
  },
  {
    name: 'Cookie',
    // 11x11, 97 tiles, 2 colors
    rows: [
      '...DDDDD...',
      '..DTTTTTD..',
      '.DTTDTTTTD.',
      'DTTTTTTDTTD',
      'DTDTTTTTTTD',
      'DTTTTDTTTTD',
      'DTTDTTTTDTD',
      'DTTTTTTTTTD',
      '.DTDTTTDTD.',
      '..DTTTTTD..',
      '...DDDDD...',
    ],
    legend: { D: DARK, T: TAN },
  },
  {
    name: 'Shark',
    // 15x10, 97 tiles, 3 colors
    rows: [
      '......DD.......',
      '.....DSSD......',
      '....DSSSSD.....',
      'D...DSSSSD.DDD.',
      'DSD.DSSSSDDSSSD',
      'DSSDDSSSSSSSSSD',
      'DSSSSSSSSSSSSSD',
      'DSWWWWWWWSSSSD.',
      '.DDWWWWWDDDDD..',
      '...DDDDD.......',
    ],
    legend: { W: WHITE, D: DARK, S: SLATE },
  },
  {
    name: 'Anchor',
    // 11x13, 99 tiles, 2 colors
    rows: [
      '....DDD....',
      '...DSSSD...',
      '...DSDSD...',
      '...DSSSD...',
      '.DDDDSDDDD.',
      'DSSSSSSSSSD',
      '.DDDDSDDDD.',
      '...DDSDD...',
      '...DSSSD...',
      'DDDDSSSDDDD',
      'DSSDSSSDSSD',
      'DSSSDDDSSSD',
      '.DDDDDDDDD.',
    ],
    legend: { D: DARK, S: SLATE },
  },
  {
    name: 'Donut',
    // 12x11, 100 tiles, 4 colors
    rows: [
      '...DDDDDD...',
      '..DMMMMMMD..',
      '.DMWMMMWMMD.',
      'DMMMDDDDMMMD',
      'DMMDD..DDMMD',
      'DMMD....DMMD',
      'DMTDD..DDTMD',
      'DTTTDDDDTTTD',
      '.DTTTTTTTTD.',
      '..DTTTTTTD..',
      '...DDDDDD...',
    ],
    legend: { M: MAGENTA, W: WHITE, D: DARK, T: TAN },
  },
  {
    name: 'Fish',
    // 14x9, 100 tiles, 3 colors
    rows: [
      '....DDDDDD....',
      '..DDOOOOOODD..',
      '.DOOOOOOOOOODD',
      'DOWWOOOOOOOOOD',
      'DOWWOOOOOOOODD',
      'DOOOOOOOOOOOOD',
      '.DOOOOOOOOOODD',
      '..DDOOOOOODD..',
      '....DDDDDD....',
    ],
    legend: { O: ORANGE, W: WHITE, D: DARK },
  },
  {
    name: 'Fox',
    // 12x11, 100 tiles, 3 colors
    rows: [
      'DD........DD',
      'DOD......DOD',
      'DOOD....DOOD',
      'DOOODDDDOOOD',
      '.DOOOOOOOOD.',
      'DOOOOOOOOOOD',
      'DOODOOOODOOD',
      'DOOOOOOOOOOD',
      '.DOOWWWWOOD.',
      '..DOWWWWOD..',
      '...DDDDDD...',
    ],
    legend: { O: ORANGE, W: WHITE, D: DARK },
  },
  {
    name: 'Starfish',
    // 13x12, 100 tiles, 2 colors
    rows: [
      '.....DDD.....',
      '.....DOD.....',
      '....DOOOD....',
      'DDDDDOOODDDDD',
      'DOOOOOOOOOOOD',
      '.DOOOOOOOOOD.',
      '..DOOOOOOOD..',
      '..DOOOOOOOD..',
      '.DOOOD.DOOOD.',
      'DOOOD...DOOOD',
      'DOOD.....DOOD',
      'DDD.......DDD',
    ],
    legend: { O: ORANGE, D: DARK },
  },
  {
    name: 'Lighthouse',
    // 11x13, 101 tiles, 4 colors
    rows: [
      '....DDD....',
      '...DYYYD...',
      '...DDDDD...',
      '..DDDDDDD..',
      '..DWWWWWD..',
      '..DRRRRRD..',
      '..DWWWWWD..',
      '.DRRRRRRRD.',
      '.DWWWWWWWD.',
      '.DRRRRRRRD.',
      'DWWWWWWWWWD',
      'DRRRRRRRRRD',
      'DDDDDDDDDDD',
    ],
    legend: { R: RED, Y: YELLOW, W: WHITE, D: DARK },
  },
  {
    name: 'Train',
    // 13x11, 101 tiles, 4 colors
    rows: [
      '.....DDDDDD..',
      '.....DSSSSD..',
      '..DDDDSSSSD..',
      '.DRRRDDDDDD..',
      'DRWWRRRRRRRD.',
      'DRWWRRRRRRRD.',
      'DRRRRRRRRRRD.',
      'DDDDDDDDDDDD.',
      '.DDD...DDD...',
      'DSSSD.DSSSD..',
      '.DDD...DDD...',
    ],
    legend: { R: RED, W: WHITE, D: DARK, S: SLATE },
  },
  {
    name: 'Whale',
    // 15x8, 101 tiles, 3 colors
    rows: [
      '...DDDDD....DD.',
      '..DBBBBBDD.DBBD',
      '.DBDBBBBBBDBBBD',
      'DBBBBBBBBBBBBBD',
      'DBBBBBBBBBBBBBD',
      'DBWWWWWWWWBBBBD',
      '.DWWWWWWWWDBBD.',
      '..DDDDDDDD.DD..',
    ],
    legend: { B: BLUE, W: WHITE, D: DARK },
  },
  {
    name: 'Crown',
    // 14x10, 102 tiles, 3 colors
    rows: [
      'D....DD....D..',
      'DD..DYYD..DD..',
      'DYD.DYYD.DYD..',
      'DYYDDYYDDYYD..',
      'DYYYYYYYYYYD..',
      'DYYYCYYCYYYD..',
      'DYYYYYYYYYYD..',
      'DDDDDDDDDDDD..',
      '.DYYYYYYYYD...',
      '.DDDDDDDDDD...',
    ],
    legend: { Y: YELLOW, C: CYAN, D: DARK },
  },
  {
    name: 'Van',
    // 14x10, 102 tiles, 4 colors
    rows: [
      '....DDDDDDD...',
      '...DWWWWWWWD..',
      'DDDDWWWWWWWD..',
      'DBBBDDDDDDDDD.',
      'DBBBBBBBBBBBD.',
      'DBBBBBBBBBBBD.',
      'DDDDDDDDDDDDD.',
      '.DDD.....DDD..',
      'DSSSD...DSSSD.',
      '.DDD.....DDD..',
    ],
    legend: { B: BLUE, W: WHITE, D: DARK, S: SLATE },
  },
  {
    name: 'Frog',
    // 13x10, 104 tiles, 3 colors
    rows: [
      '.DDD.....DDD.',
      'DWWWD...DWWWD',
      'DWDWD...DWDWD',
      'DWWWDDDDDWWWD',
      '.DGGGGGGGGGD.',
      'DGGGGGGGGGGGD',
      'DGGGGGGGGGGGD',
      'DGGGGGGGGGGGD',
      '.DGGDDDDDGGD.',
      '..DD.....DD..',
    ],
    legend: { G: GREEN, W: WHITE, D: DARK },
  },
  {
    name: 'Mushroom',
    // 13x12, 104 tiles, 3 colors
    rows: [
      '...DDDDDD....',
      '..DRRRRRRD...',
      '.DRRWRRRRRD..',
      'DRRRRRRWRRRD.',
      'DRWRRRRRRRRD.',
      'DRRRRRWRRRRD.',
      '.DDDDDDDDDD..',
      '...DWWWWD....',
      '...DWWWWD....',
      '...DWWWWD....',
      '..DDWWWWDD...',
      '..DDDDDDDD...',
    ],
    legend: { R: RED, W: WHITE, D: DARK },
  },
  {
    name: 'Panda',
    // 12x10, 104 tiles, 2 colors
    rows: [
      '.DDD....DDD.',
      'DDDDD..DDDDD',
      'DDDDDDDDDDDD',
      '.DWWWWWWWWD.',
      'DWWWWWWWWWWD',
      'DWDDWWWWDDWD',
      'DWDDWWWWDDWD',
      'DWWWWDDWWWWD',
      '.DWWWWWWWWD.',
      '..DDDDDDDD..',
    ],
    legend: { W: WHITE, D: DARK },
  },
  {
    name: 'Rocket',
    // 12x16, 104 tiles, 6 colors
    rows: [
      '.....DD.....',
      '....DWWD....',
      '...DWWWWD...',
      '...DWCCWD...',
      '...DWCCWD...',
      '...DWWWWD...',
      '..DWWWWWWD..',
      '.DMWWWWWWMD.',
      'DMMWWWWWWMMD',
      'DMMDWWWWDMMD',
      '.DDDWWWWDDD.',
      '....DOOD....',
      '...DOOOOD...',
      '...DOYYOD...',
      '....DOOD....',
      '.....DD.....',
    ],
    legend: { Y: YELLOW, C: CYAN, O: ORANGE, M: MAGENTA, W: WHITE, D: DARK },
  },
  {
    name: 'Rose',
    // 11x14, 104 tiles, 3 colors
    rows: [
      '...DDDDD...',
      '..DRRRRRD..',
      '.DRRDDDRRD.',
      'DRRDRRRDRRD',
      'DRRDRDRDRRD',
      'DRRDRRRDRRD',
      '.DRRDDDRRD.',
      '..DRRRRRD..',
      '...DDDDD...',
      '....DGD....',
      '..DDDGDDD..',
      '.DGGDGDGGD.',
      '..DDDGDDD..',
      '....DDD....',
    ],
    legend: { R: RED, G: GREEN, D: DARK },
  },
  {
    name: 'Book',
    // 12x9, 106 tiles, 3 colors
    rows: [
      '.DDDDDDDDDD.',
      'DWWWWDDWWWWD',
      'DWWWWDDWWWWD',
      'DWWWWDDWWWWD',
      'DWWWWDDWWWWD',
      'DWWWWDDWWWWD',
      'DRRRRDDRRRRD',
      'DRRRRDDRRRRD',
      'DDDDDDDDDDDD',
    ],
    legend: { R: RED, W: WHITE, D: DARK },
  },
  {
    name: 'Camera',
    // 13x9, 106 tiles, 3 colors
    rows: [
      '...DDDD......',
      'DDDDDDDDDDDD.',
      'DSSSSSSSSSSDD',
      'DSSDDDDDSSSSD',
      'DSDCCCCCDSSSD',
      'DSDCCCCCDSSSD',
      'DSSDDDDDSSSSD',
      'DSSSSSSSSSSDD',
      'DDDDDDDDDDDD.',
    ],
    legend: { C: CYAN, D: DARK, S: SLATE },
  },
  {
    name: 'Pig',
    // 12x11, 106 tiles, 3 colors
    rows: [
      '..DD....DD..',
      '.DMMD..DMMD.',
      '.DMMMDDMMMD.',
      '..DMMMMMMD..',
      '.DMMMMMMMMD.',
      'DMMDMMMMDMMD',
      'DMMMMMMMMMMD',
      'DMMMDWWDMMMD',
      'DMMMDWWDMMMD',
      '.DMMMMMMMMD.',
      '..DDDDDDDD..',
    ],
    legend: { M: MAGENTA, W: WHITE, D: DARK },
  },
  {
    name: 'Robot',
    // 11x14, 106 tiles, 3 colors
    rows: [
      '....D......',
      '....D......',
      '..DDDDDDD..',
      '.DSSSSSSSD.',
      'DSCCSSSCCSD',
      'DSCCSSSCCSD',
      'DSSSSSSSSSD',
      'DSSDDDDDSSD',
      '.DSSSSSSSD.',
      '..DDDDDDD..',
      '.DDSSSSSDD.',
      '.DSSSSSSSD.',
      '.DDD...DDD.',
      '.DD.....DD.',
    ],
    legend: { C: CYAN, D: DARK, S: SLATE },
  },
  {
    name: 'Cow',
    // 13x10, 108 tiles, 3 colors
    rows: [
      '.DD.......DD.',
      'DWWD.....DWWD',
      'DWWDDDDDDDWWD',
      '.DDWWWWWWWDD.',
      'DDWWDWWWDWWDD',
      'DWWWWWWWWWWWD',
      'DWWWWWWWWWWWD',
      'DWWDMMMMMMDWD',
      '.DDDMDMMDMDD.',
      '..DDDDDDDDD..',
    ],
    legend: { M: MAGENTA, W: WHITE, D: DARK },
  },
  {
    name: 'Pineapple',
    // 11x14, 108 tiles, 3 colors
    rows: [
      '....DDD....',
      '...DGDGD...',
      '..DGDGDGD..',
      '..DDGDGDD..',
      '...DDDDD...',
      '..DYYYYYD..',
      '.DYDYDYDYD.',
      'DYDYDYDYDYD',
      'DYDYDYDYDYD',
      'DYDYDYDYDYD',
      'DYDYDYDYDYD',
      '.DYDYDYDYD.',
      '..DYYYYYD..',
      '...DDDDD...',
    ],
    legend: { Y: YELLOW, G: GREEN, D: DARK },
  },
  {
    name: 'Clock',
    // 12x12, 110 tiles, 2 colors
    rows: [
      '...DDDDDD...',
      '..DWWWWWWD..',
      '.DWWWWWWWWD.',
      'DWWWWDWWWWWD',
      'DWWWWDWWWWWD',
      'DWWWWDDDWWWD',
      'DWWWWWWWWWWD',
      'DWWWWWWWWWWD',
      '.DWWWWWWWWD.',
      '..DWWWWWWD..',
      '...DDDDDD...',
      '...D....D...',
    ],
    legend: { W: WHITE, D: DARK },
  },
  {
    name: 'Cupcake',
    // 11x12, 110 tiles, 3 colors
    rows: [
      '...DDDDD...',
      '..DMMMMMD..',
      '.DMMMMMMMD.',
      'DMMMMMMMMMD',
      'DMMMMMMMMMD',
      '.DMMMMMMMD.',
      'DDDDDDDDDDD',
      'DBBDBBDBBBD',
      'DBBDBBDBBBD',
      '.DBDBBDBBD.',
      '.DBBBBBBBD.',
      '..DDDDDDD..',
    ],
    legend: { B: BLUE, M: MAGENTA, D: DARK },
  },
  {
    name: 'Penguin',
    // 11x13, 110 tiles, 3 colors
    rows: [
      '...DDDDD...',
      '..DDDDDDD..',
      '.DDWWDWWDD.',
      '.DDDWDWDDD.',
      '.DDDDODDDD.',
      'DDDDWWWDDDD',
      'DDDDWWWDDDD',
      'DDDDWWWDDDD',
      '.DDDWWWDDD.',
      '.DDDWWWDDD.',
      '..DDWWWDD..',
      '..DDDDDDD..',
      '..DOD.DOD..',
    ],
    legend: { O: ORANGE, W: WHITE, D: DARK },
  },
  {
    name: 'Octopus',
    // 12x11, 112 tiles, 2 colors
    rows: [
      '...DDDDDD...',
      '..DPPPPPPD..',
      '.DPPPPPPPPD.',
      'DPPDPPPPDPPD',
      'DPPPPPPPPPPD',
      'DPPPPPPPPPPD',
      '.DPPPPPPPPD.',
      'DPDPDDDDPDPD',
      'DPDPD..DPDPD',
      'DPDPD..DPDPD',
      'DDDDD..DDDDD',
    ],
    legend: { P: PURPLE, D: DARK },
  },
  {
    name: 'Bear',
    // 12x11, 116 tiles, 3 colors
    rows: [
      '.DDD....DDD.',
      'DTTTD..DTTTD',
      'DTTTDDDDTTTD',
      '.DTTTTTTTTD.',
      'DTTTTTTTTTTD',
      'DTTDTTTTDTTD',
      'DTTTTTTTTTTD',
      'DTTTDWWDTTTD',
      'DTTTDWWDTTTD',
      '.DTTTDDTTTD.',
      '..DDDDDDDD..',
    ],
    legend: { W: WHITE, D: DARK, T: TAN },
  },
  {
    name: 'Snowman',
    // 11x14, 116 tiles, 3 colors
    rows: [
      '...DDDDD...',
      '..DDDDDDD..',
      '..DWWWWWD..',
      '.DWDWWWDWD.',
      '.DWWWOWWWD.',
      '.DWWDDDWWD.',
      '..DWWWWWD..',
      '.DWWWWWWWD.',
      'DWWWDWWWWWD',
      'DWWWWWWDWWD',
      'DWWWWWWWWWD',
      '.DWWWWWWWD.',
      '..DWWWWWD..',
      '...DDDDD...',
    ],
    legend: { O: ORANGE, W: WHITE, D: DARK },
  },
  {
    name: 'Envelope',
    // 13x9, 117 tiles, 3 colors
    rows: [
      'DDDDDDDDDDDDD',
      'DWWWWWWWWWWWD',
      'DWDWWWWWWWDWD',
      'DWWDWWWWWDWWD',
      'DWWWDWWWDWWWD',
      'DWWWWDMDWWWWD',
      'DWWWWMMMWWWWD',
      'DWWWWWMWWWWWD',
      'DDDDDDDDDDDDD',
    ],
    legend: { M: MAGENTA, W: WHITE, D: DARK },
  },
  {
    name: 'Cake',
    // 15x12, 120 tiles, 4 colors
    rows: [
      '...D..D..D.....',
      '...D..D..D.....',
      '..DDDDDDDD.....',
      '.DWWWWWWWWD....',
      'DMMMMMMMMMMD...',
      'DMMMMMMMMMMD...',
      'DDDDDDDDDDDD...',
      'DWWWWWWWWWWD...',
      'DWWWWWWWWWWD...',
      'DDDDDDDDDDDD...',
      'DCCCCCCCCCCD...',
      'DDDDDDDDDDDD...',
    ],
    legend: { C: CYAN, M: MAGENTA, W: WHITE, D: DARK },
  },
  {
    name: 'Dice',
    // 11x11, 121 tiles, 2 colors
    rows: [
      'DDDDDDDDDDD',
      'DWWWWWWWWWD',
      'DWDDWWWDDWD',
      'DWDDWWWDDWD',
      'DWWWWWWWWWD',
      'DWWWDDDWWWD',
      'DWWWDDDWWWD',
      'DWDDWWWDDWD',
      'DWDDWWWDDWD',
      'DWWWWWWWWWD',
      'DDDDDDDDDDD',
    ],
    legend: { W: WHITE, D: DARK },
  },
  {
    name: 'Burger',
    // 13x11, 123 tiles, 5 colors
    rows: [
      '...DDDDDDD...',
      '..DYYYYYYYD..',
      '.DYYWYYWYYYD.',
      'DYYYYYYYYYYYD',
      '.DDDDDDDDDDD.',
      'DGGGGGGGGGGGD',
      'DRRRRRRRRRRRD',
      'DDDDDDDDDDDDD',
      'DYYYYYYYYYYYD',
      '.DYYYYYYYYYD.',
      '..DDDDDDDDD..',
    ],
    legend: { R: RED, Y: YELLOW, G: GREEN, W: WHITE, D: DARK },
  },
  {
    name: 'Pufferfish',
    // 13x11, 123 tiles, 2 colors
    rows: [
      '..D.D.D.D.D..',
      '.DDDDDDDDDDD.',
      'DDYYYYYYYYYDD',
      'DYYYYYYYYYYYD',
      'DYYDYYYYYDYYD',
      'DYYYYYYYYYYYD',
      'DYYYYDDDYYYYD',
      'DYYYYYYYYYYYD',
      'DDYYYYYYYYYDD',
      '.DDDDDDDDDDD.',
      '..D.D.D.D.D..',
    ],
    legend: { Y: YELLOW, D: DARK },
  },
  {
    name: 'Sheep',
    // 13x11, 123 tiles, 3 colors
    rows: [
      '..DDDDDDDDD..',
      '.DWWWWWWWWWD.',
      'DWWWWWWWWWWWD',
      'DWWWWWWWWWWWD',
      'DWWWWWWWWWWWD',
      '.DWWWWWWWWWD.',
      '.DDDDSSSDDDD.',
      'DSSDSSSSSDSSD',
      'DSSDSDSDSDSSD',
      '.DDDSSSSSDDD.',
      '....DDDDD....',
    ],
    legend: { W: WHITE, D: DARK, S: SLATE },
  },
  {
    name: 'Snowflake',
    // 13x15, 123 tiles, 2 colors
    rows: [
      '.....DDD.....',
      '.D...DCD...D.',
      'DCD..DCD..DCD',
      '.DCD.DCD.DCD.',
      '..DCDDCDDCD..',
      '...DCCCCCD...',
      'DDDDCCCCCDDDD',
      'DCCCCCCCCCCCD',
      'DDDDCCCCCDDDD',
      '...DCCCCCD...',
      '..DCDDCDDCD..',
      '.DCD.DCD.DCD.',
      'DCD..DCD..DCD',
      '.D...DCD...D.',
      '.....DDD.....',
    ],
    legend: { C: CYAN, D: DARK },
  },
  {
    name: 'Trophy',
    // 11x14, 124 tiles, 3 colors
    rows: [
      '.DDDDDDDDD.',
      '.DYYYYYYYD.',
      'DDYYYYYYYDD',
      'DSDYYYYYDSD',
      'DSDYYYYYDSD',
      'DSDDYYYDDSD',
      'DSSDYYYDSSD',
      '.DDDYYYDDD.',
      '...DYYYD...',
      '...DYYYD...',
      '..DDYYYDD..',
      '..DYYYYYD..',
      '.DYYYYYYYD.',
      '.DDDDDDDDD.',
    ],
    legend: { Y: YELLOW, D: DARK, S: SLATE },
  },
  {
    name: 'Present',
    // 12x12, 126 tiles, 3 colors
    rows: [
      '..DD....DD..',
      '.DYYD..DYYD.',
      '.DYYYDDYYYD.',
      '..DDYYYYDD..',
      'DDDDYYYYDDDD',
      'DRRRDYYDRRRD',
      'DRRRDYYDRRRD',
      'DDDDDYYDDDDD',
      'DRRRDYYDRRRD',
      'DRRRDYYDRRRD',
      'DRRRDYYDRRRD',
      'DDDDDDDDDDDD',
    ],
    legend: { R: RED, Y: YELLOW, D: DARK },
  },
  {
    name: 'House',
    // 15x13, 127 tiles, 5 colors
    rows: [
      '.......D.......',
      '......DRD......',
      '.....DRRRD.....',
      '....DRRRRRD....',
      '...DRRRRRRRD...',
      '..DRRRRRRRRRD..',
      '.DDDDDDDDDDDDD.',
      '.DYYYYYYYYYYYD.',
      '.DYBBYYYYYBBYD.',
      '.DYBBYYYYYBBYD.',
      '.DYYYYWWWYYYYD.',
      '.DYYYYWWWYYYYD.',
      '.DDDDDDDDDDDDD.',
    ],
    legend: { R: RED, B: BLUE, Y: YELLOW, W: WHITE, D: DARK },
  },
  {
    name: 'Drum',
    // 13x11, 128 tiles, 3 colors
    rows: [
      '..DDDDDDDDD..',
      '.DWWWWWWWWWD.',
      'DWWWWWWWWWWWD',
      'DDDDDDDDDDDDD',
      'DRRDRRRRRDRRD',
      'DRRRDRRRDRRRD',
      'DRRRRDRDRRRRD',
      'DRRRDRRRDRRRD',
      'DRRDRRRRRDRRD',
      'DDDDDDDDDDDDD',
      '.DD.......DD.',
    ],
    legend: { R: RED, W: WHITE, D: DARK },
  },
  {
    name: 'Good dog',
    // 16x13, 134 tiles, 5 colors
    rows: [
      '....DD....DD....',
      '...DOOD..DOOD...',
      '...DOTD..DOTD...',
      '..DDOODDDDOODD..',
      '..DOOOOOOOOOOD..',
      '..DOODOOOODOOD..',
      '..DOOOOOOOOOOD..',
      '..DOOWWWWWWOOD..',
      '..DOWWDDDDWWOD..',
      '..DOWWWMMWWWOD..',
      '..DDOWWWWWWODD..',
      '...DDOOOOOODD...',
      '....DDDDDDDD....',
    ],
    legend: { O: ORANGE, M: MAGENTA, W: WHITE, D: DARK, T: TAN },
  },
  {
    name: 'Cat',
    // 14x13, 140 tiles, 4 colors
    rows: [
      '..DD......DD..',
      '..DGD....DGD..',
      '..DGGD..DGGD..',
      '.DDGGGDDGGGDD.',
      '.DGGGGGGGGGGD.',
      'DGGGDGGGGDGGGD',
      'DGGGDGGGGDGGGD',
      'DGGGGGGGGGGGGD',
      'DGGWWWMMWWGGGD',
      'DGGWWWWWWWGGGD',
      '.DGGWWWWWGGGD.',
      '..DDGGGGGGDD..',
      '....DDDDDD....',
    ],
    legend: { G: GREEN, M: MAGENTA, W: WHITE, D: DARK },
  },
  {
    name: 'Sun',
    // 13x13, 141 tiles, 3 colors
    rows: [
      '....DDDDD....',
      '..DDOOOOODD..',
      '.DOOOOOOOOOD.',
      'DOOODDDDDOOOD',
      'DOODYYYYYDOOD',
      'DOODYYYYYDOOD',
      'DOODYYYYYDOOD',
      'DOODYYYYYDOOD',
      'DOODYYYYYDOOD',
      'DOOODDDDDOOOD',
      '.DOOOOOOOOOD.',
      '..DDOOOOODD..',
      '....DDDDD....',
    ],
    legend: { Y: YELLOW, O: ORANGE, D: DARK },
  },
  {
    name: 'Butterfly',
    // 17x15, 168 tiles, 4 colors
    rows: [
      '..DDD.......DDD..',
      '.DMMMDD...DDMMMD.',
      'DMMMMMMD.DMMMMMMD',
      'DMMPPMMMDMMMPPMMD',
      'DMMPPMMMDMMMPPMMD',
      'DMMMMMMMDMMMMMMMD',
      '.DMMMMMMDMMMMMMD.',
      '..DDMMMMDMMMMDD..',
      '....DMMMDMMMD....',
      '...DCCMMDMMCCD...',
      '...DCCCMDMCCCD...',
      '....DCCCDCCCD....',
      '.....DCCDCCD.....',
      '......DDDDD......',
      '.......DDD.......',
    ],
    legend: { P: PURPLE, C: CYAN, M: MAGENTA, D: DARK },
  },
  {
    name: 'Owl',
    // 16x14, 188 tiles, 5 colors
    rows: [
      '..DD........DD..',
      '.DTTD......DTTD.',
      '.DTTTDDDDDDTTTD.',
      'DTTTTTTTTTTTTTTD',
      'DTTWWWWTTWWWWTTD',
      'DTTWYYWTTWYYWTTD',
      'DTTWYYWTTWYYWTTD',
      'DTTWWWWTTWWWWTTD',
      'DTTTTTOOTTTTTTTD',
      'DTTTTTOOTTTTTTTD',
      '.DTTTTTTTTTTTTD.',
      '.DTTTTTTTTTTTTD.',
      '..DTTTTTTTTTTD..',
      '...DDDDDDDDDD...',
    ],
    legend: { Y: YELLOW, O: ORANGE, W: WHITE, D: DARK, T: TAN },
  },
];

export const PICTURE_COUNT = PICTURES.length;

export function picture(index: number): LibraryPicture {
  const found = PICTURES[index];
  if (!found) throw new Error(`picture: no picture at index ${index}`);
  return found;
}
