import type { PictureSource } from './picture';
import { BLUE, CYAN, DARK, GREEN, MAGENTA, ORANGE, PURPLE, RED, SLATE, TAN, WHITE, YELLOW } from './palette';

/**
 * The picture library.
 *
 * A level is a picture, a setting and a seed — nothing else — so this is
 * the only place artwork lives, and the generator builds every level in
 * the campaign out of it. Adding a picture here adds one level per
 * setting, so the campaign grows five at a time.
 *
 * Ordered by **measured difficulty**, which is the order the campaign
 * sweeps them in. Not by tile count: that was the first attempt and it
 * put the 903-tile Owl at the end of every run when 98% of its deals were
 * winnable — the biggest picture was one of the easiest levels in the
 * game, because most of it was a single colour and a colour that abundant
 * is always reachable.
 *
 * The rank is two measures added together: what fraction of a hundred
 * deals the solver can actually win, at each of the three tightest
 * settings, and how many tiles the picture has. Either alone gets one end
 * wrong — hardness alone finishes on a two-colour Panda, size alone
 * finishes on something trivial. Together a run opens on a small
 * forgiving picture and closes on a big unforgiving one.
 *
 * Adding a picture means re-ranking: `tools/rank-pictures.js` prints the
 * order and the emitter writes this file in it.
 *
 * Every picture is drawn with an outline, because the outline is what
 * makes the level a puzzle — it seals its own fill in, so the order the
 * picture opens up in is the thing the player is actually solving.
 *
 * Three rules `levels.test.ts` checks rather than trusting: every row of a
 * picture is the same width, no two colors in one picture sit closer than
 * the distance rule allows (which is what keeps `red` and `tan` — 142
 * apart — off the same artwork), and every name is unique.
 */
export interface LibraryPicture extends PictureSource {
  name: string;
}

export const PICTURES: readonly LibraryPicture[] = [
  {
    name: 'Heart',
    // 16x14, 156 tiles, 2 colors
    rows: [
      '...DD......DD...',
      '.DDDDDD..DDDDDD.',
      '.DDRRDDDDDDRRDD.',
      'DDRRRRRDDRRRRRDD',
      'DDRRRRRRRRRRRRDD',
      'DDRRRRRRRRRRRRDD',
      'DDRRRRRRRRRRRRDD',
      '.DDRRRRRRRRRRDD.',
      '.DDRRRRRRRRRRDD.',
      '...DDRRRRRRDD...',
      '...DDRRRRRRDD...',
      '.....DDRRDD.....',
      '.....DDDDDD.....',
      '.......DD.......',
    ],
    legend: { R: RED, D: DARK },
  },
  {
    name: 'Star',
    // 18x18, 170 tiles, 2 colors
    rows: [
      '........DD........',
      '.......DDDD.......',
      '.......DYYD.......',
      '......DDYYDD......',
      '......DDYYDD......',
      '.....DDDYYDDD.....',
      'DDDDDDDDYYDDDDDDDD',
      'DDDDDDDYYYYDDDDDDD',
      '.DDDYYYYYYYYYYDDD.',
      '...DYYYYYYYYYYD...',
      '....DDYYYYYYDD....',
      '....DDYYYYYYDD....',
      '...DYYYYDDYYYYD...',
      '.DDYYYYYDDYYYYYDD.',
      '.DYYYD......DYYYD.',
      'DDYYD........DYYDD',
      'DD..............DD',
      'DD..............DD',
    ],
    legend: { Y: YELLOW, D: DARK },
  },
  {
    name: 'Chick',
    // 18x18, 232 tiles, 3 colors
    rows: [
      '.......DDDD.......',
      '.....DDDDDDDD.....',
      '.....DYYYYYYD.....',
      '...DDYYYYYYYYDD...',
      '...DYYDDYYDDYYD...',
      '..DDYYDDYYDDYYDD..',
      '..DDYYYYOOYYYYDD..',
      '..DDYYYYOOYYYYDD..',
      '..DDYYYYYYYYYYDD..',
      '.DDDYYYYYYYYYYDDD.',
      '.DDDYYYYYYYYYYDDD.',
      'DDDYYYYYYYYYYYYDDD',
      'DDYYYYYYYYYYYYYYDD',
      '.DYYYYYYYYYYYYYYD.',
      '.DDYYYYYYYYYYYYDD.',
      '...DDYYYYYYYYDD...',
      '...DDDDDDDDDDDD...',
      '.....DDDDDDDD.....',
    ],
    legend: { Y: YELLOW, O: ORANGE, D: DARK },
  },
  {
    name: 'Duck',
    // 24x18, 236 tiles, 3 colors
    rows: [
      '.........DDDD...........',
      '.......DDDDDDDD.........',
      '.......DWWWWWDD.........',
      '.....DDWWWWWWWDD........',
      '.....DWWDDWWWWDD........',
      '...DDDWWDDWWWWDD........',
      '..DDOOOWWWWWWWDD........',
      '..DDOOOOWWWWWWDDD.......',
      '...DDDDDDDWWWWDDDDD.....',
      '.....DDDDDWWWWWDDDDDD...',
      '......DDDWWWWWWWWWWDD...',
      '......DWWWWWWWWWWWWWDD..',
      '.....DDWWWWWWWWWWWWWDD..',
      '....DDWWWWWWWWWWWWWDD...',
      '....DDWWWWWWWWWWWWWDD...',
      '.....DDWWWWWWWWWWDD.....',
      '.....DDDDDDDDDDDDDD.....',
      '.......DDDDDDDDDD.......',
    ],
    legend: { O: ORANGE, W: WHITE, D: DARK },
  },
  {
    name: 'Banana',
    // 22x20, 240 tiles, 2 colors
    rows: [
      '...............DDDD...',
      '.............DDDDDDD..',
      '.............DDDYYDD..',
      '...........DDDDYYYDD..',
      '...........DDDDYYYDD..',
      '.........DDDDYYYYYDD..',
      '.DD......DDDDYYYYYDD..',
      'DDDDD..DDDDYYYYYYDD...',
      'DDYYDDDDDYYYYYYYYDD...',
      'DDYYYDDYYYYYYYYYDD....',
      'DDYYYYYYYYYYYYYYDD....',
      '.DDYYYYYYYYYYYYYDD....',
      '.DDYYYYYYYYYYYYYDD....',
      '..DDYYYYYYYYYYYDD.....',
      '..DDYYYYYYYYYYYDD.....',
      '...DDYYYYYYYYDD.......',
      '...DDYYYYYYYYDD.......',
      '.....DDYYYYDD.........',
      '.....DDDDDDDD.........',
      '.......DDDD...........',
    ],
    legend: { Y: YELLOW, D: DARK },
  },
  {
    name: 'Lightning',
    // 18x28, 242 tiles, 2 colors
    rows: [
      '...........DD.....',
      '.........DDDDD....',
      '.........DYYDD....',
      '.......DDYYYDD....',
      '.......DDYYYDD....',
      '.....DDYYYYYDD....',
      '.....DDYYYYYDD....',
      '....DDYYYYYDD.....',
      '....DDYYYYYDD.....',
      '...DDYYYYYDD......',
      '...DDYYYYYDD......',
      '..DDYYYYYDDDD.....',
      '..DDYYDDDDDDDDD...',
      '.DDYYYDDDDDDDDDD..',
      '.DYYYYYYYYYYYDDD..',
      'DDYYYYYYYYYYYYDD..',
      'DDDDDDDDDYYYYYDD..',
      '.DDDDDDDDDYYYYDD..',
      '........DDYYYYDD..',
      '........DYYYYDD...',
      '.......DDYYYYDD...',
      '......DDYYYDD.....',
      '......DDYYYDD.....',
      '.....DDYYYD.......',
      '.....DYYYDD.......',
      '....DDYYD.........',
      '....DDDDD.........',
      '.....DD...........',
    ],
    legend: { Y: YELLOW, D: DARK },
  },
  {
    name: 'Kite',
    // 22x28, 270 tiles, 3 colors
    rows: [
      '.........DD...........',
      '.......DDDDDD.........',
      '.......DDMYDD.........',
      '.....DDMMMYYYDD.......',
      '.....DDMMMYYYDD.......',
      '...DDMMMMMYYYYYDD.....',
      '...DDMMMMMYYYYYDD.....',
      '.DDMMMMMMMYYYYYYYDD...',
      '.DDMMMMMMMYYYYYYYDD...',
      'DDMMMMMMMMYYYYYYYYDD..',
      'DDMMMMMMMMYYYYYYYYDD..',
      '.DDMMMMMMMYYYYYYYDD...',
      '.DDMMMMMMMYYYYYYYDD...',
      '...DDMMMMMYYYYYDD.....',
      '...DDMMMMMYYYYYDD.....',
      '.....DDMMMYYYDD.......',
      '.....DDMMMYYYDD.......',
      '.......DDMYDD.........',
      '.......DDDDDD.........',
      '........DDDD..........',
      '........DDDD..........',
      '.......DDDD...........',
      '......DDDD............',
      '......DDDD............',
      '........DDDD..........',
      '........DDDD..........',
      '......DDDDD...........',
      '......DDD.............',
    ],
    legend: { Y: YELLOW, M: MAGENTA, D: DARK },
  },
  {
    name: 'Key',
    // 26x18, 272 tiles, 2 colors
    rows: [
      '.....DDDDDD...............',
      '...DDDDDDDDDD.............',
      '...DDYYYYYYDD.............',
      '.DDYYYYYYYYYYDD...........',
      '.DDYYYYDDYYYYDDDDDDDDDD...',
      'DDYYYDDDDDDYYYYDDDDDDDDDD.',
      'DDYYYDD..DDYYYYYYYYYYYYYD.',
      'DDYYDD....DDYYYYYYYYYYYYDD',
      'DDYYDD....DDYYYDDDDYYYYDDD',
      'DDYYYDD..DDYYYDDDDDDYYDDD.',
      'DDYYYDDDDDDYYYDDDDDDYYDDD.',
      '.DDYYYYDDYYYYDDDDDDDYYDD..',
      '.DDYYYYYYYYYYDD....DDDDD..',
      '...DDYYYYYYDD........DD...',
      '...DDDDDDDDDD.............',
      '.....DDDDDD...............',
      '..........................',
      '..........................',
    ],
    legend: { Y: YELLOW, D: DARK },
  },
  {
    name: 'Flower',
    // 26x26, 280 tiles, 4 colors
    rows: [
      '.........DDDD.............',
      '.......DDDDDDDD...........',
      '.......DDMMMMDD...........',
      '.....DDMMMMMMMMDD.........',
      '.....DDMMMMMMMMDD.........',
      '...DDMMMMMMMMMMMMDD.......',
      '...DDMMMMMYYMMMMMDD.......',
      '..DDMMMMMYYYYMMMMMDD......',
      '..DDMMMMYYYYYYMMMMDD......',
      '...DDMMMYYYYYYMMMDD.......',
      '...DDMMMMYYYYMMMMDD.......',
      '.....DDMMMYYMMMDD.........',
      '.....DDMMMMMMMMDD.........',
      '.......DDMMMMDD...........',
      '........DDGGDD............',
      '........DGGGGD............',
      '.......DGGGGGGD...........',
      '.....DDGGGGGGGGDD.........',
      '.....DGGDDGGDDGGD.........',
      '...DDGGGDDGGDDGGGDD.......',
      '..DDGGGDD.GG.DDGGGDD......',
      '..DDGGD...GG...DGGDD......',
      '..........GG..............',
      '..........GG..............',
      '........DDDDDD............',
      '........DDDDDD............',
    ],
    legend: { Y: YELLOW, G: GREEN, M: MAGENTA, D: DARK },
  },
  {
    name: 'Bat',
    // 28x16, 283 tiles, 2 colors
    rows: [
      '..DD....................DD..',
      '.DDDD..................DDDD.',
      '.DPPD........DD........DPPD.',
      'DDPPPDD....DDDDDD....DDPPPDD',
      'DDPPPDD....DDPPDD....DDPPPDD',
      'DDPPPPPD..DDPPPPDD..DPPPPPDD',
      'DDPPPPPDDDDDPPPPDDDDDPPPPPDD',
      'DDPPPPPPPDDPPPPPPDDPPPPPPPDD',
      'DDPPPPPPPPPPPPPPPPPPPPPPPPDD',
      '.DDPPPPPPPPPPPPPPPPPPPPPPDD.',
      '.DDPPPPPPPDDPPPPDDPPPPPPPDD.',
      '...DDPPPPDDDDPPDDDDPPPPDD...',
      '...DDPPPPD..DDDD..DPPPPDD...',
      '.....DPPD....DD....DPPDD....',
      '.....DDDD.............DD....',
      '......DD..............DD....',
    ],
    legend: { P: PURPLE, D: DARK },
  },
  {
    name: 'Raindrop',
    // 18x26, 290 tiles, 2 colors
    rows: [
      '........DD........',
      '.......DDDD.......',
      '.......DCCD.......',
      '......DDCCDD......',
      '......DDCCDD......',
      '.....DDCCCCDD.....',
      '.....DDCCCCDD.....',
      '....DDCCCCCCDD....',
      '....DDCCCCCCDD....',
      '...DDCCCCCCCCDD...',
      '...DDCCCCCCCCDD...',
      '..DDCCCCCCCCCCDD..',
      '..DDCCCCCCCCCCDD..',
      '.DDCCCCCCCCCCCCDD.',
      '.DDCCCCCCCCCCCCDD.',
      'DDCCCCCCCCCCCCCCDD',
      'DDCCCCCCCCCCCCCCDD',
      'DDCCCCCCCCCCCCCCDD',
      'DDCCCCCCCCCCCCCCDD',
      '.DDCCCCCCCCCCCCDD.',
      '.DDCCCCCCCCCCCCDD.',
      '...DDCCCCCCCCDD...',
      '...DDCCCCCCCCDD...',
      '.....DDCCCCDD.....',
      '.....DDDDDDDD.....',
      '.......DDDD.......',
    ],
    legend: { C: CYAN, D: DARK },
  },
  {
    name: 'Moon',
    // 22x26, 296 tiles, 2 colors
    rows: [
      '.......DDDDDD.........',
      '.....DDDDDDDDDD.......',
      '.....DDYYYYYYYD.......',
      '...DDYYYYYYYYYDD......',
      '...DDYYYYYYYYDDD......',
      '.DDYYYYYYYYDDDD.......',
      '.DDYYYYYYYYDDDD.......',
      'DDYYYYYYYDDDD.........',
      'DDYYYYYYYDDDD.........',
      'DDYYYYYYDDD...........',
      'DDYYYYYYDDD...........',
      'DDYYYYYYDD............',
      'DDYYYYYYDD............',
      'DDYYYYYYDD............',
      'DDYYYYYYDD............',
      'DDYYYYYYDDD...........',
      'DDYYYYYYDDD...........',
      'DDYYYYYYYDDDD.........',
      'DDYYYYYYYDDDD.........',
      '.DDYYYYYYYYDDDD.......',
      '.DDYYYYYYYYDDDD.......',
      '...DDYYYYYYYYDDD......',
      '...DDYYYYYYYYYDD......',
      '.....DDYYYYYYYD.......',
      '.....DDDDDDDDDD.......',
      '.......DDDDDD.........',
    ],
    legend: { Y: YELLOW, D: DARK },
  },
  {
    name: 'Snake',
    // 26x24, 254 tiles, 2 colors
    rows: [
      '.........DDDDDDDD.........',
      '.......DDDDDDDDDDDD.......',
      '.......DGGGGGGGGGGD.......',
      '.....DDGGGGGGGGGGGGDD.....',
      '.....DGGDDGGGGGGDDGGD.....',
      '....DDGGDDGGGGGGDDGGDD....',
      '....DDGGGGGGGGGGGGGGDD....',
      '.....DDGGGGGGGGGGGGDD.....',
      '.....DDGGGGGGGGGGGGDD.....',
      '.......DDGGGGGGGGDD.......',
      '........DDGGGGGGGDD.......',
      '........DDGGGGGDD.........',
      '.......DDGGGGGGDD.........',
      '.....DDGGGGGGDD...........',
      '.....DDGGGGGGDD...........',
      '....DDGGGGGDD.............',
      '....DDGGGGGDD.............',
      '...DDGGGGDD...............',
      '...DDGGGGDD...............',
      '..DDGGGDD.................',
      '..DDGGGDD.................',
      '..DDGGD...................',
      '..DDDDD...................',
      '...DD.....................',
    ],
    legend: { G: GREEN, D: DARK },
  },
  {
    name: 'Pine',
    // 22x28, 320 tiles, 3 colors
    rows: [
      '.........DD...........',
      '.......DDDDDD.........',
      '.......DDGGDD.........',
      '......DDGGGGDD........',
      '......DDGGGGDD........',
      '.....DDGGGGGGDD.......',
      '.....DDGGGGGGDD.......',
      '....DDGGGGGGGGDD......',
      '....DDGGGGGGGGDD......',
      '...DDGGGGGGGGGGDD.....',
      '...DDGGGGGGGGGGDD.....',
      '..DDGGGGGGGGGGGGDD....',
      '..DDGGGGGGGGGGGGDD....',
      '.DDGGGGGGGGGGGGGGDD...',
      '.DDGGGGGGGGGGGGGGDD...',
      'DDGGGGGGGGGGGGGGGGDD..',
      'DDGGGGGGGGGGGGGGGGDD..',
      '.DDGGGGGGGGGGGGGGDD...',
      '.DDDDDDDDDDDDDDDDDD...',
      '...DDDDDDDDDDDDDD.....',
      '.......DDDTTDDD.......',
      '........DDTTDD........',
      '........DDTTDD........',
      '........DDTTDD........',
      '........DDTTDD........',
      '.......DDDTTDDD.......',
      '......DDDDDDDDDD......',
      '......DDDDDDDDDD......',
    ],
    legend: { G: GREEN, D: DARK, T: TAN },
  },
  {
    name: 'Balloon',
    // 20x28, 306 tiles, 3 colors
    rows: [
      '.......DDDDDD.......',
      '.....DDDDDDDDDD.....',
      '.....DDMMMMMMDD.....',
      '...DDMMMMMMMMMMDD...',
      '...DDMMMMMMMMMMDD...',
      '.DDMMMMMMMMMMMMMMDD.',
      '.DDMMMMMWWMMMMMMMDD.',
      'DDMMMMMMWWMMMMMMMMDD',
      'DDMMMMMMWWMMMMMMMMDD',
      'DDMMMMMMWWMMMMMMMMDD',
      'DDMMMMMMMMMMMMMMMMDD',
      '.DDMMMMMMMMMMMMMMDD.',
      '.DDMMMMMMMMMMMMMMDD.',
      '...DDMMMMMMMMMMDD...',
      '...DDMMMMMMMMMMDD...',
      '.....DDMMMMMMDD.....',
      '.....DDMMMMMMDD.....',
      '.......DDMMDD.......',
      '.......DDDDDD.......',
      '........DDDD........',
      '........DDDD........',
      '.......DDDDD........',
      '......DDDDDD........',
      '......DDDDDD........',
      '.......DDDDD........',
      '........DDDD........',
      '........DDDD........',
      '.........DD.........',
    ],
    legend: { M: MAGENTA, W: WHITE, D: DARK },
  },
  {
    name: 'Tree',
    // 22x26, 336 tiles, 3 colors
    rows: [
      '.........DDDD.........',
      '.......DDDDDDDD.......',
      '.......DDGGGGDD.......',
      '.....DDGGGGGGGGDD.....',
      '.....DDGGGGGGGGDD.....',
      '...DDGGGGGGGGGGGGDD...',
      '...DDGGGGGGGGGGGGDD...',
      '.DDGGGGGGGGGGGGGGGGDD.',
      'DDGGGGGGGGGGGGGGGGGGDD',
      'DDGGGGGGGGGGGGGGGGGGDD',
      '.DDGGGGGGGGGGGGGGGGDD.',
      '...DDGGGGGGGGGGGGDD...',
      '....DDGGGGGGGGGGDD....',
      '....DDGGGGGGGGGGDD....',
      '..DDGGGGGGGGGGGGGGDD..',
      '..DDGGGGGGGGGGGGGGDD..',
      '...DDGGGGGGGGGGGGDD...',
      '.....DDGGGGGGGGDD.....',
      '.....DDDDDTTDDDDD.....',
      '.......DDDTTDDD.......',
      '.......DDDTTDDD.......',
      '........DDTTDD........',
      '........DDTTDD........',
      '.......DDDTTDDD.......',
      '......DDDDDDDDDD......',
      '......DDDDDDDDDD......',
    ],
    legend: { G: GREEN, D: DARK, T: TAN },
  },
  {
    name: 'Leaf',
    // 22x26, 340 tiles, 3 colors
    rows: [
      '...............DDDD...',
      '.............DDDDDDD..',
      '...........DDDDGGDDD..',
      '.........DDDDGGGGGDD..',
      '.......DDDDGGGGGGGDD..',
      '.....DDDDGGGGGGGGGDD..',
      '.....DDGGGGGDDGGGGDD..',
      '...DDGGGGGGDDDGGGGDD..',
      '...DDGGGGGDDDGGGGGDD..',
      '..DDGGGGGDDDGGGGGGDD..',
      '..DDGGGGDDDGGGGGGGDD..',
      '.DDGGGGDDDGGGGGGGGDD..',
      '.DDGGGDDDGGGGGGGGGDD..',
      'DDGGGDDDGGGGGGGGGGDD..',
      'DDGGDDDGGGGGGGGGGGDD..',
      'DDGGDDGGGGGGGGGGGDD...',
      'DDGGDDGGGGGGGGGGGDD...',
      '.DGGDDGGGGGGGGGDD.....',
      '.DDDDDGGGGGGGGGDD.....',
      '...DDDDGGGGGGDD.......',
      '.....DDDDDDDDDD.......',
      '.......DDDDDDD........',
      '.......DDDTTDD........',
      '........DDTTD.........',
      '........DDDDD.........',
      '.........DD...........',
    ],
    legend: { G: GREEN, D: DARK, T: TAN },
  },
  {
    name: 'Cactus',
    // 22x28, 324 tiles, 3 colors
    rows: [
      '.........DDDD.........',
      '.......DDDDDDDD.......',
      '......DDMMMMMMDD......',
      '......DDMMMMMMDD......',
      '.......DDDDDDDD.......',
      '........DDDDDD........',
      '........DDGGDD........',
      '........DDGGDD........',
      '...DD...DDGGDD...DD...',
      '.DDDDD..DDGGDD..DDDDD.',
      '.DGGDD..DDGGDD..DDGGD.',
      'DDGGDD..DDGGDD..DDGGDD',
      'DDGGDDDDDDGGDDDDDDGGDD',
      'DDGGGDDDDDGGDDDDDGGGDD',
      'DDGGGGGGDDGGDDGGGGGGDD',
      '.DDGGGGGDDGGDDGGGGGDD.',
      '.DDDDDDDDDGGDDDDDDDDD.',
      '...DDDDDDDGGDDDDDDD...',
      '.......DDDGGDDD.......',
      '........DDGGDD........',
      '........DDGGDD........',
      '.......DDGGGGDD.......',
      '.......DDGGGGDD.......',
      '......DDGGGGGGDD......',
      '......DDGGGGGGDD......',
      '......DDDGGGGDDD......',
      '......DDDDDDDDDD......',
      '.......DDDDDDDD.......',
    ],
    legend: { G: GREEN, M: MAGENTA, D: DARK },
  },
  {
    name: 'Guitar',
    // 22x28, 348 tiles, 2 colors
    rows: [
      '.........DDDD.........',
      '........DDDDDD........',
      '........DDTTDD........',
      '........DDTTDD........',
      '........DDTTDD........',
      '........DDTTDD........',
      '........DDTTDD........',
      '........DDTTDD........',
      '........DDTTDD........',
      '........DDTTDD........',
      '........DDTTDD........',
      '.......DDDTTDDD.......',
      '.......DDDTTDDD.......',
      '.....DDDDTTTTDDDD.....',
      '.....DDTTTTTTTTDD.....',
      '...DDTTTTTTTTTTTTDD...',
      '...DDTTTTDDDDTTTTDD...',
      '.DDTTTTTDDDDDDTTTTTDD.',
      '.DDTTTTTDDDDDDTTTTTDD.',
      'DDTTTTTTTDDDDTTTTTTTDD',
      'DDTTTTTTTDDDDTTTTTTTDD',
      'DDTTTTTTTTDDTTTTTTTTDD',
      'DDTTTTTTTTTTTTTTTTTTDD',
      '.DDTTTTTTTTTTTTTTTTDD.',
      '.DDTTTTTTTTTTTTTTTTDD.',
      '...DDTTTTTTTTTTTTDD...',
      '...DDDDDDDDDDDDDDDD...',
      '.....DDDDDDDDDDDD.....',
    ],
    legend: { D: DARK, T: TAN },
  },
  {
    name: 'Fried egg',
    // 22x20, 352 tiles, 3 colors
    rows: [
      '.........DDDDDD.......',
      '.......DDDDDDDDDD.....',
      '.....DDDDWWWWWWDDDD...',
      '...DDDDWWWWWWWWWWDDDD.',
      '...DDWWWWWWWWWWWWWWDD.',
      '.DDWWWWWWWWWWWWWWWWWDD',
      '.DDWWWWWWDDDDWWWWWWWDD',
      'DDWWWWWDDDDDDDDWWWWWDD',
      'DDWWWWWDDYYYYDDWWWWWDD',
      'DDWWWWDDYYYYYYDDWWWWDD',
      'DDWWWWDDYYYYYYDDWWWWDD',
      'DDWWWWWDDYYYYDDWWWWWDD',
      'DDWWWWWDDDDDDDDWWWWWDD',
      '.DDWWWWWWDDDDWWWWWWWDD',
      '.DDWWWWWWWWWWWWWWWWWDD',
      '...DDWWWWWWWWWWWWWWDD.',
      '...DDWWWWWWWWWWWWDDDD.',
      '.....DDWWWWWWWWDDDD...',
      '.....DDDDDDDDDDDD.....',
      '.......DDDDDDDD.......',
    ],
    legend: { Y: YELLOW, W: WHITE, D: DARK },
  },
  {
    name: 'Shell',
    // 24x20, 340 tiles, 3 colors
    rows: [
      '...........DD...........',
      '.........DDDDDD.........',
      '.......DDDDMMDDDD.......',
      '.....DDDDMMMMMMDDDD.....',
      '.....DMMMMMMMMMMMMD.....',
      '...DDMMMMMMMMMMMMMMDD...',
      '...DMMDDMMMMMMMMDDMMD...',
      '.DDMMMDDDMMMMMMDDDMMMDD.',
      '.DMMDDMMDDMMMMDDMMDDMMD.',
      'DDMMDDMMDDMMMMDDMMDDMMDD',
      'DDMMDDMMDDMMMMDDMMDDMMDD',
      'DDMMDDMMDDMMMMDDMMDDMMDD',
      'DDMMMMMMMMMMMMMMMMMMMMDD',
      '.DDMMMMMMMMMMMMMMMMMMDD.',
      '.DDMMMMMMMMMMMMMMMMMMDD.',
      '...DDMMMMMMMMMMMMMMDD...',
      '...DDDWWWWWWWWWWWWDDD...',
      '.....DDWWWWWWWWWWDD.....',
      '.....DDDDDDDDDDDDDD.....',
      '.......DDDDDDDDDD.......',
    ],
    legend: { M: MAGENTA, W: WHITE, D: DARK },
  },
  {
    name: 'Cloud',
    // 28x16, 332 tiles, 3 colors
    rows: [
      '...........DDDDDD...........',
      '.........DDDDDDDDDD.........',
      '.......DDDDWWWWWWDDDD.......',
      '.....DDDDWWWWWWWWWWDDDD.....',
      '.....DDWWWWWWWWWWWWWWDD.....',
      '...DDWWWWWWWWWWWWWWWWWWDD...',
      '...DDWWWWWWWWWWWWWWWWWWDD...',
      '.DDWWWWWWWWWWWWWWWWWWWWWWDD.',
      '.DDWWWWWWWWWWWWWWWWWWWWWWDD.',
      'DDWWWWWWWWWWWWWWWWWWWWWWWWDD',
      'DDWWWWWWWWWWWWWWWWWWWWWWWWDD',
      '.DDWWWWWWWWWWWWWWWWWWWWWWDD.',
      '.DDDSSSSSSSSSSSSSSSSSSSSDDD.',
      '...DDSSSSSSSSSSSSSSSSSSDD...',
      '...DDDDDDDDDDDDDDDDDDDDDD...',
      '.....DDDDDDDDDDDDDDDDDD.....',
    ],
    legend: { W: WHITE, D: DARK, S: SLATE },
  },
  {
    name: 'Carrot',
    // 18x28, 270 tiles, 3 colors
    rows: [
      '...DD........DD...',
      '.DDDDDD....DDDDDD.',
      '.DDGGDD....DDGGDD.',
      'DDGGGGGD..DGGGGGDD',
      'DDGGGGGDDDDGGGGGDD',
      '.DDGGGGGDDGGGGGDD.',
      '.DDGGGGGDDGGGGGDD.',
      '...DDGGDDDDGGDD...',
      '...DDDDGGGGDDDD...',
      '....DDDDGGDDDD....',
      '....DDDOOOODDD....',
      '....DDOOOOOODD....',
      '....DDOOOOOODD....',
      '....DDOOOOOODD....',
      '....DDOOOOOODD....',
      '....DDOOOOOODD....',
      '....DDOOOOOODD....',
      '.....DDOOOOODD....',
      '.....DDOOOOODD....',
      '......DDOOOODD....',
      '......DDOOOODD....',
      '......DDOOODD.....',
      '......DDOOODD.....',
      '......DDOODD......',
      '......DDOODD......',
      '.......DOODD......',
      '.......DDDDD......',
      '.........DD.......',
    ],
    legend: { G: GREEN, O: ORANGE, D: DARK },
  },
  {
    name: 'Apple',
    // 20x22, 308 tiles, 4 colors
    rows: [
      '...........DD.......',
      '.........DDDDDD.....',
      '.........DDGGGD.....',
      '.......DDDGGGGDD....',
      '.....DDDDDRRDDDD....',
      '...DDDDDDRRRRDDDD...',
      '...DDRRRRRRRRRRDD...',
      '.DDRRRRRRRRRRRRRRDD.',
      '.DDRRRWWRRRRRRRRRDD.',
      'DDRRRRWWRRRRRRRRRRDD',
      'DDRRRRWWRRRRRRRRRRDD',
      'DDRRRRWWRRRRRRRRRRDD',
      'DDRRRRRRRRRRRRRRRRDD',
      'DDRRRRRRRRRRRRRRRRDD',
      'DDRRRRRRRRRRRRRRRRDD',
      '.DDRRRRRRRRRRRRRRDD.',
      '.DDRRRRRRRRRRRRRRDD.',
      '...DDRRRRRRRRRRDD...',
      '...DDRRRRRRRRRRDD...',
      '.....DDRRRRRRDD.....',
      '.....DDDDDDDDDD.....',
      '.......DDDDDD.......',
    ],
    legend: { R: RED, G: GREEN, W: WHITE, D: DARK },
  },
  {
    name: 'Bell',
    // 22x24, 324 tiles, 2 colors
    rows: [
      '.........DD...........',
      '.......DDDDDD.........',
      '.......DDDDDD.........',
      '.....DDDDDDDDDD.......',
      '.....DDYYYYYYDD.......',
      '...DDYYYYYYYYYYDD.....',
      '...DDYYYYYYYYYYDD.....',
      '..DDYYYYYYYYYYYYDD....',
      '..DDYYYYYYYYYYYYDD....',
      '.DDYYYYYYYYYYYYYYDD...',
      '.DDYYYYYYYYYYYYYYDD...',
      'DDYYYYYYYYYYYYYYYYDD..',
      'DDYYYYYYYYYYYYYYYYDD..',
      'DDYYYYYYYYYYYYYYYYDD..',
      'DDYYYYYYYYYYYYYYYYDD..',
      'DDDYYYYYYYYYYYYYYDDD..',
      'DDDDDDDDDDDDDDDDDDDD..',
      '.DDDDDDDDDDDDDDDDDD...',
      '.DDDDDYYYYYYYYDDDDD...',
      '...DDDYYYYYYYYDDD.....',
      '.....DDYYYYYYDD.......',
      '.......DDYYDD.........',
      '.......DDDDDD.........',
      '.........DD...........',
    ],
    legend: { Y: YELLOW, D: DARK },
  },
  {
    name: 'Candy',
    // 26x18, 336 tiles, 3 colors
    rows: [
      '.DD....................DD.',
      'DDDDD................DDDDD',
      'DDDDD................DDDDD',
      'DDDDDDD............DDDDDDD',
      'DDMMDDDDDDDDDDDDDDDDDDMMDD',
      'DDMMMDDDDDDDDDDDDDDDDMMMDD',
      'DDMMMDDDDMMMMMMMMDDDDMMMDD',
      'DDMMMMDDMMMMMMMMMMDDMMMMDD',
      'DDMMMMDDMMWWWWWWMMDDMMMMDD',
      'DDMMMMDDMMWWWWWWMMDDMMMMDD',
      'DDMMMMDDMMMMMMMMMMDDMMMMDD',
      'DDMMMDDDDMMMMMMMMDDDDMMMDD',
      'DDMMMDDDDDDDDDDDDDDDDMMMDD',
      'DDMMDDDDDDDDDDDDDDDDDDMMDD',
      'DDDDDDD............DDDDDDD',
      'DDDDD................DDDDD',
      'DDDDD................DDDDD',
      '.DD....................DD.',
    ],
    legend: { M: MAGENTA, W: WHITE, D: DARK },
  },
  {
    name: 'Ghost',
    // 20x22, 372 tiles, 3 colors
    rows: [
      '.......DDDDDD.......',
      '.....DDDDDDDDDD.....',
      '.....DDWWWWWWDD.....',
      '...DDWWWWWWWWWWDD...',
      '...DDWWWWWWWWWWDD...',
      '.DDWWWWWWWWWWWWWWDD.',
      '.DDWWWDDWWWWDDWWWDD.',
      'DDWWWWDDWWWWDDWWWWDD',
      'DDWWWWDDWWWWDDWWWWDD',
      'DDWWWWDDWWWWDDWWWWDD',
      'DDWWWWWWWWWWWWWWWWDD',
      'DDWWWWWWWWWWWWWWWWDD',
      'DDWWWWWWWWWWWWWWWWDD',
      'DDWWWWWWWWWWWWWWWWDD',
      'DDWWWWMMMMMMMMWWWWDD',
      'DDWWWWMMMMMMMMWWWWDD',
      'DDWWWWWWWWWWWWWWWWDD',
      'DDWWWWWWWWWWWWWWWDDD',
      'DDWWDDWWWWDDWWWWWDDD',
      'DDWWDDWWWDDDWWWDDDD.',
      'DDDDDD..DDDD..DDDDD.',
      '.DDDD....DD....DD...',
    ],
    legend: { M: MAGENTA, W: WHITE, D: DARK },
  },
  {
    name: 'Mountain',
    // 28x20, 348 tiles, 3 colors
    rows: [
      '.............DD.............',
      '...........DDDDDD...........',
      '...........DDWWDD...........',
      '.........DDWWWWWWDD.........',
      '.........DWWWWWWWDD.........',
      '.......DDWWWWWWWWWWDD.......',
      '.......DWWWDDDDWWWWWD.......',
      '.....DDDWWDDDDDDDWWWWDD.....',
      '.....DSSDDDDD..DDDDWWWD.....',
      '....DDSSSDDD.....DDDWWDD....',
      '....DDSSSDDD......DDSSDD....',
      '...DDSSSSSSDD.....DSSSSDD...',
      '...DDSSSSSSDD....DDSSSSDD...',
      '.DDSSSSSSSSSSD..DSSSSSSSSDD.',
      '.DDSSSSSSSSSSDDDDSSSSSSSSDD.',
      'DDSSSSSSSSSSSSDDSSSSSSSSSSDD',
      'DDSSSSSSSSSSSSSSSSSSSSSSSSDD',
      'DDDSSSSSSSSSSSSSSSSSSSSSSDDD',
      'DDDDDDDDDDDDDDDDDDDDDDDDDDDD',
      '.DDDDDDDDDDDDDDDDDDDDDDDDDD.',
    ],
    legend: { W: WHITE, D: DARK, S: SLATE },
  },
  {
    name: 'Lolly',
    // 20x28, 320 tiles, 4 colors
    rows: [
      '.......DDDDDD.......',
      '.....DDDDDDDDDD.....',
      '.....DDMWWMMMDD.....',
      '...DDMMWWWWMMMMDD...',
      '...DDMWWMMWWMMMDD...',
      '.DDMMWWWMMWWWMMMMDD.',
      '.DDMWWMMMMMWWWMMMDD.',
      'DDMMWWMMMMMMWWWMMMDD',
      'DDMMMWWWMMMMMWWWMMDD',
      'DDMMMMWWWMMMMMWWWMDD',
      'DDMMMMMWWWMMMMMWMWDD',
      '.DDMMMMMWWWMMMMMWDD.',
      '.DDMMMMMMWWWMMMMDDD.',
      '...DDMMMMMWWWMMDD...',
      '...DDMMMMMMWMWDDD...',
      '.....DDMMMMMWDD.....',
      '.....DDDDDDDDDD.....',
      '.......DDDDDDD......',
      '.......DDDTTDD......',
      '........DDTTDD......',
      '........DDTTDD......',
      '........DDTTDD......',
      '........DDTTDD......',
      '........DDTTDD......',
      '........DDTTDD......',
      '........DDTTDD......',
      '........DDDDDD......',
      '.........DDDD.......',
    ],
    legend: { M: MAGENTA, W: WHITE, D: DARK, T: TAN },
  },
  {
    name: 'Turtle',
    // 26x18, 330 tiles, 3 colors
    rows: [
      '.........DDDDDDDD.........',
      '.......DDDDDDDDDDDD.......',
      '.......DGGGGGGGGGGD.......',
      '.....DDGGGGGGGGGGGGDD.....',
      '.....DGGDDDDDDDDDDGGD.....',
      '...DDGGGDDDDDDDDDDGGGDD...',
      '...DGGDDDGGGGGGGGDDDGGD...',
      '.DDDGGDDGGGGGGGGGGDDGGDDD.',
      '.DYYDGDGGGDDGGDDGGGDGDYYD.',
      'DDYYDDGGGGDDGGDDGGGGDDYYDD',
      'DDYYDDGGGGGGGGGGGGGGDDYYDD',
      '.DYYDGDGGGGGGGGGGGGDGDYYD.',
      '.DDDGGDDGGGGGGGGGGDDGGDDD.',
      '...DGGDDDGGGGGGGGDDDGGD...',
      '...DDDDDDDDDDDDDDDDDDDD...',
      '.....DDDDDDDDDDDDDDDD.....',
      '.....DDDYYDD..DDYYDDD.....',
      '.......DYYD....DYYD.......',
    ],
    legend: { Y: YELLOW, G: GREEN, D: DARK },
  },
  {
    name: 'Bunny',
    // 22x24, 378 tiles, 3 colors
    rows: [
      '...DD........DD.......',
      '.DDDDDD....DDDDDD.....',
      '.DDWWDD....DDWWDD.....',
      'DDWWWWDD..DDWWWWDD....',
      'DDWWWMDD..DDWWWMDD....',
      'DDWWMMDD..DDWWMMDD....',
      'DDWWMMDD..DDWWMMDD....',
      'DDWWWMDD..DDWWWMDD....',
      'DDWWWWDD..DDWWWWDD....',
      '.DDWWWWD..DDWWWWDD....',
      '.DDWWWWDDDDDWWWWDD....',
      '..DDWWWWWDDWWWWWDD....',
      '..DDWWWWWWWWWWWWDD....',
      '.DDWWWWWWWWWWWWWWDD...',
      '.DDWWWDDWWWWDDWWWDD...',
      'DDWWWWDDWWWWDDWWWWDD..',
      'DDWWWWWWWWWWWWWWWWDD..',
      'DDWWWWWWWWWWWWWWWWDD..',
      'DDWWWWWWMMWWWWWWWWDD..',
      '.DDWWWWWMMWWWWWWWDD...',
      '.DDWWWWWWWWWWWWWWDD...',
      '...DDWWWWWWWWWWDD.....',
      '...DDDDDDDDDDDDDD.....',
      '.....DDDDDDDDDD.......',
    ],
    legend: { M: MAGENTA, W: WHITE, D: DARK },
  },
  {
    name: 'Starfish',
    // 26x24, 394 tiles, 2 colors
    rows: [
      '...........DDDD...........',
      '..........DDDDDD..........',
      '..........DDOODD..........',
      '.........DDOOOODD.........',
      '.........DDOOOODD.........',
      '.......DDDOOOOOODDD.......',
      '.DDDDDDDDDOOOOOODDDDDDDDD.',
      'DDDDDDDDDOOOOOOOODDDDDDDDD',
      'DDOOOOOOOOOOOOOOOOOOOOOODD',
      '.DOOOOOOOOOOOOOOOOOOOOOOD.',
      '.DDOOOOOOOOOOOOOOOOOOOODD.',
      '...DDOOOOOOOOOOOOOOOODD...',
      '...DDOOOOOOOOOOOOOOOODD...',
      '....DDOOOOOOOOOOOOOODD....',
      '....DDOOOOOOOOOOOOOODD....',
      '...DDOOOOOOOOOOOOOOOODD...',
      '...DDOOOOOOD..DOOOOOODD...',
      '.DDOOOOOODD....DDOOOOOODD.',
      '.DDOOOOOODD....DDOOOOOODD.',
      'DDOOOOODD........DDOOOOODD',
      'DDOOOOODD........DDOOOOODD',
      'DDDOODD............DDOODDD',
      'DDDDDDD............DDDDDDD',
      '.DDDD................DDDD.',
    ],
    legend: { O: ORANGE, D: DARK },
  },
  {
    name: 'Jellyfish',
    // 22x24, 376 tiles, 2 colors
    rows: [
      '.......DDDDDDDD.......',
      '.....DDDDDDDDDDDD.....',
      '.....DDMMMMMMMMDD.....',
      '...DDMMMMMMMMMMMMDD...',
      '...DDMMMMMMMMMMMMDD...',
      '.DDMMMMMMMMMMMMMMMMDD.',
      '.DDMMMMMMMMMMMMMMMMDD.',
      'DDMMMMMMMMMMMMMMMMMMDD',
      'DDMMMMDDMMMMMMDDMMMMDD',
      'DDMMMMDDMMMMMMDDMMMMDD',
      'DDMMMMMMMMMMMMMMMMMMDD',
      '.DDMMMMMMMMMMMMMMMMDD.',
      '.DDMMMMMMMMMMMMMMMMDD.',
      '..DDDMMMMMMMMMMMMDDD..',
      '..DDDDDDDDDDDDDDDDDD..',
      '..DDDDDDDDDDDDDDDDD...',
      '..DDMMDD..DDMMDDD.....',
      '..DDMMDD..DDMMDD......',
      '..DDMMDD..DDMMDD......',
      '...DMMMD...DMMMDD.....',
      '...DDMMMD...DMMMD.....',
      '....DDMMDD..DDMMDD....',
      '....DDDDDD..DDDDDD....',
      '.....DDDD....DDDD.....',
    ],
    legend: { M: MAGENTA, D: DARK },
  },
  {
    name: 'Bulb',
    // 22x26, 356 tiles, 3 colors
    rows: [
      '.......DDDDDD.........',
      '.....DDDDDDDDDD.......',
      '.....DDYYYYYYDD.......',
      '...DDYYYYYYYYYYDD.....',
      '...DDYYYYYYYYYYDD.....',
      '.DDYYYYYYYYYYYYYYDD...',
      '.DDYYYYYYYYYYYYYYDD...',
      'DDYYYYYYYYYYYYYYYYDD..',
      'DDYYYYYYYYYYYYYYYYDD..',
      'DDYYYYYYYYYYYYYYYYDD..',
      'DDYYYYYYYYYYYYYYYYDD..',
      '.DDYYYYYYYYYYYYYYDD...',
      '.DDYYYYYYYYYYYYYYDD...',
      '...DDYYYYYYYYYYDD.....',
      '...DDYYYYYYYYYYDD.....',
      '....DDYYYYYYYYDD......',
      '....DDSSSSSSSSDD......',
      '....DDDSSSSSSDDD......',
      '....DDDDDDDDDDDD......',
      '....DDDDDDDDDDDD......',
      '....DDSSSSSSSSDD......',
      '....DDSSSSSSSSDD......',
      '....DDDDDDDDDDDD......',
      '.....DDDDDDDDDD.......',
      '.....DDDDSSDDDD.......',
      '.......DSSSSD.........',
    ],
    legend: { Y: YELLOW, D: DARK, S: SLATE },
  },
  {
    name: 'Candle',
    // 18x28, 258 tiles, 3 colors
    rows: [
      '........DD........',
      '.......DDDD.......',
      '.......DYYD.......',
      '......DDYYDD......',
      '......DDYYDD......',
      '.....DDYYYYDD.....',
      '.....DDYYYYDD.....',
      '....DDYYYYYYDD....',
      '....DDYYYYYYDD....',
      '.....DDYYYYDD.....',
      '.....DDYYYYDD.....',
      '.......DYYD.......',
      '........DD........',
      '........DD........',
      '.....DDDDDDDD.....',
      '...DDDDDDDDDDDD...',
      '...DDWWWWWWWWDD...',
      '..DDWWWWWWWWWWDD..',
      '..DDWWWWWWWWWWDD..',
      '..DDWWWWWWWWWWDD..',
      '..DDWWWWWWWWWWDD..',
      '..DDWWWWWWWWWWDD..',
      '..DDWWWWWWWWWWDD..',
      '..DDWWWWWWWWWWDD..',
      '..DDWWWWWWWWWWDD..',
      '...DDWWWWWWWWDD...',
      '...DDDDDDDDDDDD...',
      '.....DDDDDDDD.....',
    ],
    legend: { Y: YELLOW, W: WHITE, D: DARK },
  },
  {
    name: 'Palm',
    // 26x28, 353 tiles, 3 colors
    rows: [
      '...DD................DD...',
      '.DDDDDD............DDDDDD.',
      'DDGGGDDDD........DDDDGGGDD',
      'DDGGGGGDDDD....DDDDGGGGGDD',
      '.DDGGGGGGDD....DDGGGGGGDD.',
      '...DDGGGGGGD..DGGGGGGDD...',
      '....DGGGGGGDDDDGGGGGGD....',
      '....DDDGGGGGDDGGGGGDDD....',
      '...DDDDDGGGGGGGGGGDDDDD...',
      '.DDDDDDDDGGGGGGGGDDDDDDDD.',
      'DDGGGGGGGDDGGGGDDGDGGGGGD.',
      'DDGGGGGGDDDDGGDDDDGGGGGGDD',
      '.DDDDDDDD..DDDDD....DDDDDD',
      '...DDDD.....DDDD.....DDDD.',
      '............DDTTD.........',
      '...........DDTTTDD........',
      '...........DDTTTDD........',
      '..........DDTTTDD.........',
      '..........DDTTDD..........',
      '..........DDTTDD..........',
      '..........DDTTTTDD........',
      '.........DDTTTTTDD........',
      '.........DDTTTTDD.........',
      '........DDTTTTDD..........',
      '........DDTTTTDD..........',
      '........DDDTTDD...........',
      '........DDDDDDD...........',
      '.........DDDD.............',
    ],
    legend: { G: GREEN, D: DARK, T: TAN },
  },
  {
    name: 'Umbrella',
    // 26x28, 374 tiles, 3 colors
    rows: [
      '...........DDDD...........',
      '.........DDDDDDDD.........',
      '.....DDDDDDMMMMDDDDDD.....',
      '...DDDDDDMMMMMMMMDDDDDD...',
      '...DDMMMMMMMMMMMMMMMMDD...',
      '.DDMMMMMMMMMMMMMMMMMMMMDD.',
      '.DDMMMMMMMMMMMMMMMMMMMMDD.',
      'DDMMMMMMMMMMMMMMMMMMMMMMDD',
      'DDMMDDMMMMMMDDMMMMMMDDMMDD',
      'DDMMDDDMMMMDDDDMMMMDDDMMDD',
      'DDDDDDDDDDDDDDDDDDDDDDDDDD',
      '.DDDDDDDDDDDDDDDDDDDDDDDD.',
      '.DDDDD..DDDD..DDDD..DDDDD.',
      '...DD....DD...DDDD...DD...',
      '...........D.DSSDD........',
      '............DDSSDD........',
      '............DDSSDD........',
      '............DDSSDD........',
      '............DDSSDD........',
      '............DDSSDDD.......',
      '............DDSSDDD.......',
      '...........DDSSSSDDD......',
      '...........DDSSSSSDD......',
      '..........DDSSSSSSDD......',
      '..........DDSSSDDDDD......',
      '..........DDSSDDDDD.......',
      '..........DDDDDDD.........',
      '...........DDDD...........',
    ],
    legend: { M: MAGENTA, D: DARK, S: SLATE },
  },
  {
    name: 'Boat',
    // 30x22, 332 tiles, 3 colors
    rows: [
      '.............DD...............',
      '............DDDDD.............',
      '............DDWWD.............',
      '............DDWWWDD...........',
      '............DDWWWDD...........',
      '............DDWWWWWDD.........',
      '............DDWWWWWDD.........',
      '............DDWWWWWWWDD.......',
      '............DDWWWWWWWWD.......',
      '............DDDWWWWWWWDD......',
      '............DDDDDDDDDDDD......',
      '...........DDDDDDDDDDDDDD.....',
      '.DDDDDDDDDDDDDDDDDDDDDDDDDD...',
      'DDDDDDDDDDDDDDDDDDDDDDDDDDDD..',
      'DDWWWWWWWWWWWWWWWWWWWWWWWWDD..',
      '.DWWWWWWWWWWWWWWWWWWWWWWWWD...',
      '.DDWWWWWWWWWWWWWWWWWWWWWWDD...',
      '...DDWWWWWWWWWWWWWWWWWWDD.....',
      '...DDDDDDDDDDDDDDDDDDDDDD.....',
      '.....DDDDDDDDDDDDDDDDDD.......',
      '.....DDDDCCCCCCCCCCDDDD.......',
      '.......DCCCCCCCCCCCCD.........',
    ],
    legend: { C: CYAN, W: WHITE, D: DARK },
  },
  {
    name: 'Lemon',
    // 24x18, 292 tiles, 3 colors
    rows: [
      '...........DDDD.........',
      '.........DDDDDDDD.......',
      '.........DGGGGGGD.......',
      '.......DDDGGGGGGDDD.....',
      '.....DDDDDDDDDDDDDD.....',
      '...DDDDDDDDDDDDDDDDDD...',
      '...DDYYYYYYYYYYYYYYDD...',
      '.DDYYYYYYYYYYYYYYYYYYDD.',
      '.DDYYYYYYYYYYYYYYYYYYDD.',
      'DDYYYYYYYYYYYYYYYYYYYYDD',
      'DDYYYYYYYYYYYYYYYYYYYYDD',
      '.DDYYYYYYYYYYYYYYYYYYDD.',
      '.DDYYYYYYYYYYYYYYYYYYDD.',
      '...DDYYYYYYYYYYYYYYDD...',
      '...DDYYYYYYYYYYYYYYDD...',
      '.....DDYYYYYYYYYYDD.....',
      '.....DDDDDDDDDDDDDD.....',
      '.......DDDDDDDDDD.......',
    ],
    legend: { Y: YELLOW, G: GREEN, D: DARK },
  },
  {
    name: 'Anchor',
    // 22x26, 396 tiles, 2 colors
    rows: [
      '.........DDDD.........',
      '.......DDDDDDDD.......',
      '.......DDSSSSDD.......',
      '......DDSSSSSSDD......',
      '......DDSSDDSSDD......',
      '......DDSSDDSSDD......',
      '......DDSSSSSSDD......',
      '.....DDDDSSSSDDDD.....',
      '...DDDDDDDSSDDDDDDD...',
      '.DDDDDDDDDSSDDDDDDDDD.',
      'DDSSSSSSSSSSSSSSSSSSDD',
      'DDSSSSSSSSSSSSSSSSSSDD',
      '.DDDDDDDDSSSSDDDDDDDD.',
      '...DDDDDDDSSDDDDDDD...',
      '.....DDDDDSSDDDDD.....',
      '......DDDSSSSDDD......',
      '......DDDSSSSDDD......',
      '.....DDDSSSSSSDDD.....',
      '.DDDDDDDSSSSSSDDDDDDD.',
      'DDDDDDDDSSSSSSDDDDDDDD',
      'DDDSSDDDSSSSSSDDDSSDDD',
      'DDSSSSDDDSSSSDDDSSSSDD',
      'DDSSSSSSSDDDDSSSSSSSDD',
      '.DDSSSSSDDDDDDSSSSSDD.',
      '.DDDDDDDDDDDDDDDDDDDD.',
      '...DDDDDDDDDDDDDDDD...',
    ],
    legend: { D: DARK, S: SLATE },
  },
  {
    name: 'Crown',
    // 28x20, 404 tiles, 3 colors
    rows: [
      'DD.........DD.........DD....',
      'DDD......DDDDDD......DDD....',
      'DDD......DDYYDD......DDD....',
      'DDDDD...DDYYYYDD...DDDDD....',
      'DDYYD...DDYYYYDD...DYYDD....',
      'DDYYYD..DDYYYYDD..DYYYDD....',
      'DDYYYDDDDDYYYYDDDDDYYYDD....',
      'DDYYYYYDDYYYYYYDDYYYYYDD....',
      'DDYYYYYYYYYYYYYYYYYYYYDD....',
      'DDYYYYYYYYYYYYYYYYYYYYDD....',
      'DDYYYYYYCCYYYYCCYYYYYYDD....',
      'DDYYYYYYCCYYYYCCYYYYYYDD....',
      'DDYYYYYYYYYYYYYYYYYYYYDD....',
      'DDDYYYYYYYYYYYYYYYYYYDDD....',
      'DDDDDDDDDDDDDDDDDDDDDDDD....',
      '.DDDDDDDDDDDDDDDDDDDDDD.....',
      '.DDDYYYYYYYYYYYYYYYYDDD.....',
      '..DDYYYYYYYYYYYYYYYYDD......',
      '..DDDDDDDDDDDDDDDDDDDD......',
      '...DDDDDDDDDDDDDDDDDD.......',
    ],
    legend: { Y: YELLOW, C: CYAN, D: DARK },
  },
  {
    name: 'Cup',
    // 24x20, 368 tiles, 3 colors
    rows: [
      '...DDDDDDDDDDDDDDDD.....',
      '..DDDDDDDDDDDDDDDDDD....',
      '..DDDWWWWWWWWWWWWDDD....',
      '..DDWWWWWWWWWWWWWWDDD...',
      '..DDWWWCCCCCCCCWWWDDD...',
      '..DDWWCCCCCCCCCCWWDDDDD.',
      '..DDWWCCCCCCCCCCWWDDWWD.',
      '..DDWWCCCCCCCCCCWWDDWWDD',
      '..DDWWCCCCCCCCCCWWDDWWDD',
      '..DDWWCCCCCCCCCCWWDDWWDD',
      '..DDWWCCCCCCCCCCWWDDDDDD',
      '..DDWWCCCCCCCCCCWWDDDDD.',
      '..DDWWCCCCCCCCCCWWDDD...',
      '..DDWWCCCCCCCCCCWWDD....',
      '..DDWWCCCCCCCCCCWWDD....',
      '...DDWWCCCCCCCCWWDD.....',
      '...DDWWWWWWWWWWWWDD.....',
      '....DDDWWWWWWWWDDD......',
      '....DDDDDDDDDDDDDD......',
      '.....DDDDDDDDDDDD.......',
    ],
    legend: { C: CYAN, W: WHITE, D: DARK },
  },
  {
    name: 'Parrot',
    // 20x26, 316 tiles, 4 colors
    rows: [
      '.......DDDDDD.......',
      '.....DDDDDDDDDD.....',
      '.....DYYYYYYYDD.....',
      '...DDYYYYYYYYYYDD...',
      '...DYYDDYYYYYYYDD...',
      '.DDDYYDDYYYYYYYYDD..',
      '.DOODYYYYYYYYYYYDD..',
      'DDOOODYYYYYYYYYYDD..',
      'DDOOODDYYYYYYYYYDD..',
      '.DDOOODDYYYYYYYYDD..',
      '.DDOOODDGGGGGGGGDD..',
      '...DOODDGGGGGGGGDD..',
      '...DDDDDGGGGGGGGDD..',
      '.....DDDGGGGGGGGDD..',
      '.....DDDGGGGGGGGDD..',
      '......DDGGGGGGGGDD..',
      '......DDGGGGGGGGDD..',
      '......DDGGGGGGGGDD..',
      '......DDGGGGGGGGDD..',
      '......DDGGGGGGGDD...',
      '......DDGGGGGGGDD...',
      '......DDGGGGGDD.....',
      '......DDGGGGGDD.....',
      '.......DDGGDD.......',
      '.......DDDDDD.......',
      '.........DD.........',
    ],
    legend: { Y: YELLOW, G: GREEN, O: ORANGE, D: DARK },
  },
  {
    name: 'Mouse',
    // 22x18, 310 tiles, 3 colors
    rows: [
      '...DD............DD...',
      '.DDDDDD........DDDDDD.',
      '.DDMMDD........DDMMDD.',
      'DDMMMMMDD....DDMMMMMDD',
      'DDMMMMMDD....DDMMMMMDD',
      '.DDMMMMMDD..DDMMMMMDD.',
      '..DDSSSSDDDDDDSSSSDD..',
      '..DSSSSSSDDDDSSSSSSD..',
      '.DDSSSSSSSSSSSSSSSSDD.',
      'DDSSSSSSSSSSSSSSSSSSDD',
      'DDSSDDSSSSSSSSSSDDSSDD',
      'DDSSDDSSSSSSSSSSDDSSDD',
      'DDSSSSSSSSMMSSSSSSSSDD',
      '.DDSSSSSSSMMSSSSSSSDD.',
      '.DDSSSSSSSSSSSSSSSSDD.',
      '...DDSSSSSSSSSSSSDD...',
      '...DDDDDDDDDDDDDDDD...',
      '.....DDDDDDDDDDDD.....',
    ],
    legend: { M: MAGENTA, D: DARK, S: SLATE },
  },
  {
    name: 'Diamond',
    // 22x22, 298 tiles, 2 colors
    rows: [
      '.....DDDDDDDDDDDD.....',
      '...DDDDDDDDDDDDDDDD...',
      '...DDCCCCDDDDCCCCDD...',
      '.DDCCCCCCCDDCCCCCCCDD.',
      '.DCCCCCCCCDDCCCCCCCCD.',
      'DDCCCCCCCDDDDCCCCCCCDD',
      'DDDDDDDDDDDDDDDDDDDDDD',
      '.DDDDDDDDDDDDDDDDDDDD.',
      '.DDDCCCCCCCCCCCCCCDDD.',
      '...DCCCCCCCCCCCCCCD...',
      '...DDCCCCCCCCCCCCDD...',
      '....DDCCCCCCCCCCDD....',
      '....DDCCCCCCCCCCDD....',
      '.....DDCCCCCCCCDD.....',
      '.....DDCCCCCCCCDD.....',
      '......DDCCCCCCDD......',
      '......DDCCCCCCDD......',
      '.......DDCCCCDD.......',
      '.......DDCCCCDD.......',
      '.........DCCD.........',
      '.........DDDD.........',
      '..........DD..........',
    ],
    legend: { C: CYAN, D: DARK },
  },
  {
    name: 'Hedgehog',
    // 28x16, 326 tiles, 3 colors
    rows: [
      '......DD..DD..DD..DD........',
      '.....DDD..DD..DD..DDD.......',
      '.....DDDDDDDDDDDDDDDD.......',
      '...DDDDDDDDDDDDDDDDDDDD.....',
      '...DDDDTTTTTTTTTTTTDDDD.....',
      '.DDDDTTTTTTTTTTTTTTTTDDDD...',
      '.DDDDTTTTTTTTTTTTTTTTDDDD...',
      'DDDTTTTTTTTTTTTTTTTTTTDDDDD.',
      'DDTTTTTTTTTTTTTTTTTTTWWWWWD.',
      '.DTTTTTTTTTTTTTTTTTWWWWWWWDD',
      '.DDTTTTTTTTTTTTTTTTWWWWDDDDD',
      '...DDTTTTTTTTTTTTTWWWWDDDDD.',
      '...DDTTTTTTTTTTTTTDWWWDDD...',
      '.....DDTTTTTTTTTTDDDWWD.....',
      '.....DDDDDDDDDDDDDDDDDD.....',
      '.......DDDDDDDDDDDDDD.......',
    ],
    legend: { W: WHITE, D: DARK, T: TAN },
  },
  {
    name: 'Cookie',
    // 22x22, 384 tiles, 2 colors
    rows: [
      '.......DDDDDDDD.......',
      '.....DDDDDDDDDDDD.....',
      '.....DDTTTTTTTTDD.....',
      '...DDTTTTTTTTTTTTDD...',
      '...DDTTTDDTTTTTTTDD...',
      '.DDTTTTTDDTTTTTTTTTDD.',
      '.DDTTTTTTTTTTTDDTTTDD.',
      'DDTTTTTTTTTTTTDDTTTTDD',
      'DDTTDDTTTTTTTTTTTTTTDD',
      'DDTTDDTTTTTTTTTTTTTTDD',
      'DDTTTTTTTTDDTTTTTTTTDD',
      'DDTTTTTTTTDDTTTTTTTTDD',
      'DDTTTTDDTTTTTTTTDDTTDD',
      'DDTTTTDDTTTTTTTTDDTTDD',
      'DDTTTTTTTTTTTTTTTTTTDD',
      '.DDTTTTTTTTTTTTTTTTDD.',
      '.DDTTTDDTTTTTTDDTTTDD.',
      '...DTTDDTTTTTTDDTTD...',
      '...DDTTTTTTTTTTTTDD...',
      '.....DTTTTTTTTTTD.....',
      '.....DDDDDDDDDDDD.....',
      '.......DDDDDDDD.......',
    ],
    legend: { D: DARK, T: TAN },
  },
  {
    name: 'Pig',
    // 24x22, 416 tiles, 3 colors
    rows: [
      '.....DD..........DD.....',
      '...DDDDDD......DDDDDD...',
      '...DDMMDD......DDMMDD...',
      '..DDMMMMMDD..DDMMMMMDD..',
      '..DDMMMMMDDDDDDMMMMMDD..',
      '...DDMMMMMMDDMMMMMMDD...',
      '....DDMMMMMMMMMMMMDD....',
      '....DDMMMMMMMMMMMMDD....',
      '...DDMMMMMMMMMMMMMMDD...',
      '.DDMMMMMMMMMMMMMMMMMMDD.',
      '.DDMMMDDMMMMMMMMDDMMMDD.',
      'DDMMMMDDMMMMMMMMDDMMMMDD',
      'DDMMMMMMMMMMMMMMMMMMMMDD',
      'DDMMMMMMMMMMMMMMMMMMMMDD',
      'DDMMMMMMMDWWWWDMMMMMMMDD',
      'DDMMMMMMDDWWWWDDMMMMMMDD',
      'DDMMMMMMDDWWWWDDMMMMMMDD',
      '.DDMMMMMMDWWWWDMMMMMMDD.',
      '.DDMMMMMMMMMMMMMMMMMMDD.',
      '...DDMMMMMMMMMMMMMMDD...',
      '...DDDDDDDDDDDDDDDDDD...',
      '.....DDDDDDDDDDDDDD.....',
    ],
    legend: { M: MAGENTA, W: WHITE, D: DARK },
  },
  {
    name: 'Shark',
    // 30x20, 381 tiles, 3 colors
    rows: [
      '.............DD...............',
      '...........DDDDDD.............',
      '...........DDSSDD.............',
      '.........DDSSSSSSDD...........',
      '.........DDSSSSSSDD...........',
      '........DDSSSSSSSSDD..........',
      'DD......DDSSSSSSSSDD...DDDD...',
      'DD......DDSSSSSSSSDD..DDDDDDD.',
      'DDSSD...DDSSSSSSSSDDDDDSSSSDD.',
      'DDSSSD..DDSSSSSSSSSDDSSSSSSSDD',
      'DDSSSDDDDDSSSSSSSSSSSSSSSSSSDD',
      'DDSSSSSDDSSSSSSSSSSSSSSSSSSSDD',
      'DDSSSSSSSSSSSSSSSSSSSSSSSSSSDD',
      'DDSSSSSSSSSSSSSSSSSSSSSSSSSDD.',
      'DDSSSWWWWWWWWWWWWSSSSSSSSSSDD.',
      '.DDSWWWWWWWWWWWWWWSSSSSSSDD...',
      '.DDDDWWWWWWWWWWWWDDDDDDDDDD...',
      '...DDDDWWWWWWWWDDDDDDDDDD.....',
      '.....DDDDDDDDDDDD.............',
      '.......DDDDDDDD...............',
    ],
    legend: { W: WHITE, D: DARK, S: SLATE },
  },
  {
    name: 'Bee',
    // 26x22, 372 tiles, 3 colors
    rows: [
      '...DD................DD...',
      '.DDDDDD............DDDDDD.',
      '.DDWWDD............DDWWDD.',
      'DDWWWWWDD........DDWWWWWDD',
      'DDWWWWWDD........DDWWWWWDD',
      '.DDWWWWWDDD....DDDWWWWWDD.',
      '.DDWWWWWDDDDDDDDDDWWWWWDD.',
      '...DDWWDDDDDDDDDDDDWWDD...',
      '...DDDDDDYYYYYYYYDDDDDD...',
      '....DDDYYYYYYYYYYYYDDD....',
      '....DDYYYYYYYYYYYYYYDD....',
      '....DDYYYYYYYYYYYYYYDD....',
      '....DDDDDDDDDDDDDDDDDD....',
      '....DDDDDDDDDDDDDDDDDD....',
      '....DDYYYYYYYYYYYYYYDD....',
      '....DDYYYYYYYYYYYYYYDD....',
      '....DDDDDDDDDDDDDDDDDD....',
      '....DDDDDDDDDDDDDDDDDD....',
      '....DDYYYYYYYYYYYYYYDD....',
      '.....DYYYYYYYYYYYYYYD.....',
      '.....DDDDDDDDDDDDDDDD.....',
      '.......DDDDDDDDDDDD.......',
    ],
    legend: { Y: YELLOW, W: WHITE, D: DARK },
  },
  {
    name: 'Snowflake',
    // 26x30, 488 tiles, 2 colors
    rows: [
      '...........DDDD...........',
      '..........DDDDDD..........',
      '..DD......DDCCDD......DD..',
      '.DDDD.....DDCCDD.....DDDD.',
      'DDCCD.....DDCCDD.....DCCDD',
      'DDCCCDD...DDCCDD...DDCCCDD',
      '.DDCCCD...DDCCDD...DCCCDD.',
      '...DCCCD..DDCCDD..DCCCD...',
      '...DDCCCDDDDCCDDDDCCCDD...',
      '.....DCCCDDCCCCDDCCCD.....',
      '......DCDCCCCCCCCDCD......',
      '......DDCCCCCCCCCCDD......',
      '.DDDDDDDCCCCCCCCCCDDDDDDD.',
      'DDDDDDDCCCCCCCCCCCCDDDDDDD',
      'DDCCCCCCCCCCCCCCCCCCCCCCDD',
      'DDCCCCCCCCCCCCCCCCCCCCCCDD',
      'DDDDDDDCCCCCCCCCCCCDDDDDDD',
      '.DDDDDDDCCCCCCCCCCDDDDDDD.',
      '......DDCCCCCCCCCCDD......',
      '......DCDCCCCCCCCDCD......',
      '.....DCCCDDCCCCDDCCCD.....',
      '...DDCCCDDDDCCDDDDCCCDD...',
      '...DCCCD..DDCCDD..DCCCD...',
      '.DDCCCD...DDCCDD...DCCCDD.',
      'DDCCCDD...DDCCDD...DDCCCDD',
      'DDCCD.....DDCCDD.....DCCDD',
      '.DDDD.....DDCCDD.....DDDD.',
      '..DD......DDCCDD......DD..',
      '..........DDDDDD..........',
      '...........DDDD...........',
    ],
    legend: { C: CYAN, D: DARK },
  },
  {
    name: 'Octopus',
    // 24x22, 440 tiles, 2 colors
    rows: [
      '.......DDDDDDDDDD.......',
      '.....DDDDDDDDDDDDDD.....',
      '.....DDPPPPPPPPPPDD.....',
      '...DDPPPPPPPPPPPPPPDD...',
      '...DDPPPPPPPPPPPPPPDD...',
      '.DDPPPPPPPPPPPPPPPPPPDD.',
      '.DDPPPDDPPPPPPPPDDPPPDD.',
      'DDPPPPDDPPPPPPPPDDPPPPDD',
      'DDPPPPPPPPPPPPPPPPPPPPDD',
      'DDPPPPPPPPPPPPPPPPPPPPDD',
      'DDPPPPPPPPPPPPPPPPPPPPDD',
      '.DDPPPPPPPPPPPPPPPPPPDD.',
      '..DDPPPPPPPPPPPPPPPPDD..',
      '..DDDPPPPPPPPPPPPPPDDD..',
      '.DPPDDPPPDDDDDDPPPDDPPD.',
      'DDPPDDPPDDDDDDDDPPDDPPDD',
      'DDPPDDPPDDD..DDDPPDDPPDD',
      'DDPPDDPPDD....DDPPDDPPDD',
      'DDPPDDPPDD....DDPPDDPPDD',
      'DDPPDDPPDD....DDPPDDPPDD',
      'DDDDDDDDDD....DDDDDDDDDD',
      '.DDDDDDDD......DDDDDDDD.',
    ],
    legend: { P: PURPLE, D: DARK },
  },
  {
    name: 'Robot',
    // 22x28, 416 tiles, 3 colors
    rows: [
      '........DD............',
      '........DD............',
      '........DD............',
      '.......DDDD...........',
      '.....DDDDDDDDDDDD.....',
      '...DDDDDDDDDDDDDDDD...',
      '...DDSSSSSSSSSSSSDD...',
      '.DDSSSSSSSSSSSSSSSSDD.',
      '.DDSSCCSSSSSSSSCCSSDD.',
      'DDSSCCCCSSSSSSCCCCSSDD',
      'DDSSCCCCSSSSSSCCCCSSDD',
      'DDSSSCCSSSSSSSSCCSSSDD',
      'DDSSSSSSSSSSSSSSSSSSDD',
      'DDSSSSSSSSSSSSSSSSSSDD',
      'DDSSSSDDDDDDDDDDSSSSDD',
      '.DDSSSDDDDDDDDDDSSSDD.',
      '.DDSSSSSSSSSSSSSSSSDD.',
      '...DDSSSSSSSSSSSSDD...',
      '....DDDDDDDDDDDDDD....',
      '....DDDDDDDDDDDDDD....',
      '...DDDDSSSSSSSSDDDD...',
      '..DDDSSSSSSSSSSSSDDD..',
      '..DDSSSSSSSSSSSSSSDD..',
      '..DDSSSSSSSSSSSSSSDD..',
      '..DDDDDD......DDDDDD..',
      '..DDDDD........DDDDD..',
      '..DDDDD........DDDDD..',
      '...DD............DD...',
    ],
    legend: { C: CYAN, D: DARK, S: SLATE },
  },
  {
    name: 'Fox',
    // 24x22, 392 tiles, 3 colors
    rows: [
      '.DD..................DD.',
      'DDDDD..............DDDDD',
      'DDOOD..............DOODD',
      'DDOOODD..........DDOOODD',
      'DDOOODD..........DDOOODD',
      'DDOOOOODD......DDOOOOODD',
      'DDOOOOODDDDDDDDDDOOOOODD',
      '.DDOOOOOODDDDDDOOOOOODD.',
      '..DDOOOOOOOOOOOOOOOODD..',
      '..DDOOOOOOOOOOOOOOOODD..',
      '.DDOOOOOOOOOOOOOOOOOODD.',
      'DDOOOOOOOOOOOOOOOOOOOODD',
      'DDOOOODDOOOOOOOODDOOOODD',
      'DDOOOODDOOOOOOOODDOOOODD',
      'DDOOOOOOOOOOOOOOOOOOOODD',
      '.DDOOOOOOOOOOOOOOOOOODD.',
      '.DDOOOOOOWWWWWWOOOOOODD.',
      '...DDOOOWWWWWWWWOOODD...',
      '...DDOOOWWWWWWWWOOODD...',
      '.....DDOWWWWWWWWODD.....',
      '.....DDDDDDDDDDDDDD.....',
      '.......DDDDDDDDDD.......',
    ],
    legend: { O: ORANGE, W: WHITE, D: DARK },
  },
  {
    name: 'Train',
    // 26x22, 400 tiles, 4 colors
    rows: [
      '...........DDDDDDDDDD.....',
      '..........DDDDDDDDDDDD....',
      '..........DDDSSSSSSDDD....',
      '.........DDDSSSSSSSSDD....',
      '.....DDDDDDDSSSSSSSSDD....',
      '...DDDDDDDDDDSSSSSSDDD....',
      '...DDRRRRDDDDDDDDDDDDD....',
      '.DDRRRRRRRRDDDDDDDDDDDD...',
      '.DDRRWWRRRRRRRRRRRRRRDD...',
      'DDRRWWWWRRRRRRRRRRRRRRDD..',
      'DDRRWWWWRRRRRRRRRRRRRRDD..',
      'DDRRRWWRRRRRRRRRRRRRRRDD..',
      'DDRRRRRRRRRRRRRRRRRRRRDD..',
      'DDDRRRRRRRRRRRRRRRRRRDDD..',
      'DDDDDDDDDDDDDDDDDDDDDDDD..',
      '.DDDDDDDDDDDDDDDDDDDDDD...',
      '..DDDDDD......DDDDDD......',
      '..DDDDDD......DDDDDD......',
      'DDSSSSSSDD..DDSSSSSSDD....',
      'DDSSSSSSDD..DDSSSSSSDD....',
      '.DDDDDDDD....DDDDDDDD.....',
      '...DDDD........DDDD.......',
    ],
    legend: { R: RED, W: WHITE, D: DARK, S: SLATE },
  },
  {
    name: 'Bear',
    // 24x22, 456 tiles, 3 colors
    rows: [
      '...DDDD..........DDDD...',
      '.DDDDDDDD......DDDDDDDD.',
      '.DDTTTTDD......DDTTTTDD.',
      'DDTTTTTTDDD..DDDTTTTTTDD',
      'DDTTTTTTDDDDDDDDTTTTTTDD',
      '.DDTTTTTTDDDDDDTTTTTTDD.',
      '..DDTTTTTTTTTTTTTTTTDD..',
      '..DDTTTTTTTTTTTTTTTTDD..',
      '.DDTTTTTTTTTTTTTTTTTTDD.',
      'DDTTTTTTTTTTTTTTTTTTTTDD',
      'DDTTTTDDTTTTTTTTDDTTTTDD',
      'DDTTTTDDTTTTTTTTDDTTTTDD',
      'DDTTTTTTTTTTTTTTTTTTTTDD',
      'DDTTTTTTTTTTTTTTTTTTTTDD',
      'DDTTTTTTTDWWWWDTTTTTTTDD',
      'DDTTTTTTDDWWWWDDTTTTTTDD',
      'DDTTTTTTDDWWWWDDTTTTTTDD',
      '.DDTTTTTTDDWWDDTTTTTTDD.',
      '.DDTTTTTTTDDDDTTTTTTTDD.',
      '...DDTTTTTDDDDTTTTTDD...',
      '...DDDDDDDDDDDDDDDDDD...',
      '.....DDDDDDDDDDDDDD.....',
    ],
    legend: { W: WHITE, D: DARK, T: TAN },
  },
  {
    name: 'Pizza',
    // 26x22, 368 tiles, 4 colors
    rows: [
      '...........DDDD...........',
      '.........DDDDDDDD.........',
      '.........DDTTTTDD.........',
      '........DDTTTTTTDD........',
      '........DDYYYYYYDD........',
      '.......DDYYYYYYYYDD.......',
      '.......DDYYYGGYYYDD.......',
      '......DDYYYYGGYYYYDD......',
      '......DDYYYYYYYYYYDD......',
      '.....DDYYYYYYYYYYYYDD.....',
      '.....DDYGGYYYYYYGGYDD.....',
      '....DDYYGGYYYYYYGGYYDD....',
      '....DDYYYYYYYYYYYYYYDD....',
      '...DDYYYYYYYYYYYYYYYYDD...',
      '...DDYYYGGYYYYYYGGYYYDD...',
      '..DDYYYYGGYYYYYYGGYYYYDD..',
      '..DDYYYYYYYYYYYYYYYYYYDD..',
      '.DDDYYYYYYYYYYYYYYYYYYDDD.',
      '.DTTTTTTTTTTTTTTTTTTTTTTD.',
      'DDTTTTTTTTTTTTTTTTTTTTTTDD',
      'DDDDDDDDDDDDDDDDDDDDDDDDDD',
      '.DDDDDDDDDDDDDDDDDDDDDDDD.',
    ],
    legend: { Y: YELLOW, G: GREEN, D: DARK, T: TAN },
  },
  {
    name: 'Fish',
    // 28x18, 396 tiles, 3 colors
    rows: [
      '.........DDDDDDDDDD.........',
      '.......DDDDDDDDDDDDDD.......',
      '.....DDDDOOOOOOOOOODDDD.....',
      '...DDDDOOOOOOOOOOOOOODDDD...',
      '...DDOOOOOOOOOOOOOOOOOODDDD.',
      '.DDOOOOOOOOOOOOOOOOOOOOOODDD',
      '.DDOOWWOOOOOOOOOOOOOOOOOOODD',
      'DDOOWWWWOOOOOOOOOOOOOOOOOODD',
      'DDOOWWWWOOOOOOOOOOOOOOOODDDD',
      'DDOOOWWOOOOOOOOOOOOOOOOODDDD',
      'DDOOOOOOOOOOOOOOOOOOOOOOOODD',
      '.DDOOOOOOOOOOOOOOOOOOOOOOODD',
      '.DDOOOOOOOOOOOOOOOOOOOOOODDD',
      '...DDOOOOOOOOOOOOOOOOOODDDD.',
      '...DDDDOOOOOOOOOOOOOODDDD...',
      '.....DDDDOOOOOOOOOODDDD.....',
      '.......DDDDDDDDDDDDDD.......',
      '.........DDDDDDDDDD.........',
    ],
    legend: { O: ORANGE, W: WHITE, D: DARK },
  },
  {
    name: 'Deer',
    // 24x24, 304 tiles, 3 colors
    rows: [
      'DD..DD............DD..DD',
      'DD..DDD..........DDD..DD',
      'DDD...DD........DD...DDD',
      '.DDD..DD........DD..DDD.',
      '.DDDDDDD........DDDDDDD.',
      '...DDDDDD......DDDDDD...',
      '...DDDDDD......DDDDDD...',
      '.....DDDDDD..DDDDDD.....',
      '.....DDDDDDDDDDDDDD.....',
      '......DDDDDDDDDDDD......',
      '......DDDTTTTTTDDD......',
      '.....DDTTTTTTTTTTDD.....',
      '.....DDTTTTTTTTTTDD.....',
      '....DDTTTTTTTTTTTTDD....',
      '....DDTTDDTTTTDDTTDD....',
      '....DDTTDDTTTTDDTTDD....',
      '....DDTTTTTTTTTTTTDD....',
      '....DDTTTTTTTTTTTTDD....',
      '....DDTTTTWWWWTTTTDD....',
      '.....DDTTTWWWWTTTDD.....',
      '.....DDTTTTTTTTTTDD.....',
      '.......DDTTTTTTDD.......',
      '.......DDDDDDDDDD.......',
      '.........DDDDDD.........',
    ],
    legend: { W: WHITE, D: DARK, T: TAN },
  },
  {
    name: 'Rose',
    // 22x28, 412 tiles, 3 colors
    rows: [
      '.......DDDDDDDD.......',
      '.....DDDDDDDDDDDD.....',
      '.....DDRRRRRRRRDD.....',
      '...DDRRRRRRRRRRRRDD...',
      '...DDRRRDDDDDDRRRDD...',
      '.DDRRRRDDDDDDDDRRRRDD.',
      '.DDRRRDDDRRRRDDDRRRDD.',
      'DDRRRRDDRRRRRRDDRRRRDD',
      'DDRRRRDDRRDDRRDDRRRRDD',
      'DDRRRRDDRRDDRRDDRRRRDD',
      'DDRRRRDDRRRRRRDDRRRRDD',
      '.DDRRRDDDRRRRDDDRRRDD.',
      '.DDRRRRDDDDDDDDRRRRDD.',
      '...DDRRRDDDDDDRRRDD...',
      '...DDRRRRRRRRRRRRDD...',
      '.....DDRRRRRRRRDD.....',
      '.....DDDDDDDDDDDD.....',
      '.......DDDDDDDD.......',
      '........DDGGDD........',
      '........DDGGDD........',
      '.....DDDDDGGDDDDD.....',
      '...DDDDDDDGGDDDDDDD...',
      '..DDGGGGDDGGDDGGGGDD..',
      '..DDGGGGDDGGDDGGGGDD..',
      '...DDDDDDDGGDDDDDDD...',
      '.....DDDDDGGDDDDD.....',
      '.......DDDDDDDD.......',
      '.........DDDD.........',
    ],
    legend: { R: RED, G: GREEN, D: DARK },
  },
  {
    name: 'Van',
    // 28x20, 404 tiles, 4 colors
    rows: [
      '.........DDDDDDDDDDDD.......',
      '.......DDDDDDDDDDDDDDDD.....',
      '.......DDWWWWWWWWWWWWDD.....',
      '.....DDDWWWWWWWWWWWWWWDD....',
      '.DDDDDDDWWWWWWWWWWWWWWDD....',
      'DDDDDDDDDWWWWWWWWWWWWDDDD...',
      'DDDBBBBDDDDDDDDDDDDDDDDDD...',
      'DDBBBBBBBDDDDDDDDDDDDDDDDD..',
      'DDBBBBBBBBBBBBBBBBBBBBBDDD..',
      'DDBBBBBBBBBBBBBBBBBBBBBBDD..',
      'DDBBBBBBBBBBBBBBBBBBBBBBDD..',
      'DDDBBBBBBBBBBBBBBBBBBBBDDD..',
      'DDDDDDDDDDDDDDDDDDDDDDDDDD..',
      '.DDDDDDDDDDDDDDDDDDDDDDDD...',
      '..DDDDDD..........DDDDDD....',
      '..DDDDDD..........DDDDDD....',
      'DDSSSSSSDD......DDSSSSSSDD..',
      'DDSSSSSSDD......DDSSSSSSDD..',
      '.DDDDDDDD........DDDDDDDD...',
      '...DDDD............DDDD.....',
    ],
    legend: { B: BLUE, W: WHITE, D: DARK, S: SLATE },
  },
  {
    name: 'Grapes',
    // 22x28, 334 tiles, 3 colors
    rows: [
      '.............DDDD.....',
      '...........DDDDDDD....',
      '...........DDGGGDD....',
      '.........DDDGGGGD.....',
      '.......DDDDDGGGDD.....',
      '.....DDDDDDDGGDD......',
      '.....DGGGGDDDDDD......',
      '....DDGGGGDDDDD.......',
      '....DDDDDDDDDD........',
      '...DDDDDDDDDDD........',
      '...DDDDDDDDDDDDDD.....',
      '.DDDDDDDDDDDDDDDDDD...',
      '.DDPPPPPPPPPPPPPPDD...',
      'DDPPPPPPPPPPPPPPPPDD..',
      'DDPPDDPPPPDDPPPPPPDD..',
      '.DPPDDPPPPDDPPPPPDD...',
      '.DDPDPPPPPPPPPPPPDD...',
      '..DDPPPPPPPPPPPPDD....',
      '..DDPPDDPPPPDDPPDD....',
      '...DPPDDPPPPDDPPD.....',
      '...DDPDPPPPPPDPDD.....',
      '....DDPPPPPPPPDD......',
      '....DDPPPPPPPPDD......',
      '.....DDPPPPPPDD.......',
      '.....DDPPPPPPDD.......',
      '.......DDPPDD.........',
      '.......DDDDDD.........',
      '.........DD...........',
    ],
    legend: { G: GREEN, P: PURPLE, D: DARK },
  },
  {
    name: 'Dice',
    // 22x22, 480 tiles, 2 colors
    rows: [
      '.DDDDDDDDDDDDDDDDDDDD.',
      'DDDDDDDDDDDDDDDDDDDDDD',
      'DDDWWWWWWWWWWWWWWWWDDD',
      'DDWWWWWWWWWWWWWWWWWWDD',
      'DDWWWDDWWWWWWWWDDWWWDD',
      'DDWWDDDDWWWWWWDDDDWWDD',
      'DDWWDDDDWWWWWWDDDDWWDD',
      'DDWWWDDWWWWWWWWDDWWWDD',
      'DDWWWWWWWWWWWWWWWWWWDD',
      'DDWWWWWWWWWWWWWWWWWWDD',
      'DDWWWWWWWDDDDWWWWWWWDD',
      'DDWWWWWWDDDDDDWWWWWWDD',
      'DDWWWWWWDDDDDDWWWWWWDD',
      'DDWWWWWDWDDDDWDWWWWWDD',
      'DDWWWDDWDWWWWDWDDWWWDD',
      'DDWWDDDDWWWWWWDDDDWWDD',
      'DDWWDDDDWWWWWWDDDDWWDD',
      'DDWWWDDWWWWWWWWDDWWWDD',
      'DDWWWWWWWWWWWWWWWWWWDD',
      'DDDWWWWWWWWWWWWWWWWDDD',
      'DDDDDDDDDDDDDDDDDDDDDD',
      '.DDDDDDDDDDDDDDDDDDDD.',
    ],
    legend: { W: WHITE, D: DARK },
  },
  {
    name: 'Whale',
    // 30x16, 396 tiles, 3 colors
    rows: [
      '.......DDDDDDDD..........DD...',
      '.....DDDDDDDDDDDD......DDDDDD.',
      '.....DBBBBBBBBBDDDD....DDBBDD.',
      '...DDBBBBBBBBBBBBDDD..DBBBBBDD',
      '...DBBDDBBBBBBBBBBBDDDDBBBBBDD',
      '.DDBBBDDBBBBBBBBBBBBDDBBBBBBDD',
      '.DDBBBBBBBBBBBBBBBBBBBBBBBBBDD',
      'DDBBBBBBBBBBBBBBBBBBBBBBBBBBDD',
      'DDBBBBBBBBBBBBBBBBBBBBBBBBBBDD',
      'DDBBBBBBBBBBBBBBBBBBBBBBBBBBDD',
      'DDBBBWWWWWWWWWWWWWWBBBBBBBBBDD',
      '.DDBWWWWWWWWWWWWWWWWBBBBBBBDD.',
      '.DDDWWWWWWWWWWWWWWWWDBBBBBBDD.',
      '...DDWWWWWWWWWWWWWWDDDDBBDD...',
      '...DDDDDDDDDDDDDDDDD..DDDDD...',
      '.....DDDDDDDDDDDDDD....DD.....',
    ],
    legend: { B: BLUE, W: WHITE, D: DARK },
  },
  {
    name: 'Ladybird',
    // 22x20, 356 tiles, 2 colors
    rows: [
      '.......DDDDDDDD.......',
      '.....DDDDDDDDDDDD.....',
      '.....DDDDDDDDDDDD.....',
      '...DDDDDDDDDDDDDDDD...',
      '...DDDDDDDDDDDDDDDD...',
      '..DDDDDDDDDDDDDDDDDD..',
      '..DDDRRRRDDDDRRRRDDD..',
      '.DDRRRRRRRDDRRRRRRRDD.',
      '.DDRRRRRRRDDRRRRRRRDD.',
      'DDRRRRRRRRDDRRRRRRRRDD',
      'DDRRDDRRRRDDRRRRDDRRDD',
      'DDRRDDRRRRDDRRRRDDRRDD',
      'DDRRRRRRRRDDRRRRRRRRDD',
      'DDRRRRRRRRDDRRRRRRRRDD',
      'DDRRRRDDRRDDRRDDRRRRDD',
      '.DDRRRDDRRDDRRDDRRRDD.',
      '.DDRRRRRRRDDRRRRRRRDD.',
      '...DDRRRRDDDDRRRRDD...',
      '...DDDDDDDDDDDDDDDD...',
      '.....DDDDDDDDDDDD.....',
    ],
    legend: { R: RED, D: DARK },
  },
  {
    name: 'Clock',
    // 24x24, 440 tiles, 2 colors
    rows: [
      '.......DDDDDDDDDD.......',
      '.....DDDDDDDDDDDDDD.....',
      '.....DDWWWWWWWWWWDD.....',
      '...DDWWWWWWWWWWWWWWDD...',
      '...DDWWWWWWWWWWWWWWDD...',
      '.DDWWWWWWWWWWWWWWWWWWDD.',
      '.DDWWWWWWWDDWWWWWWWWWDD.',
      'DDWWWWWWWWDDWWWWWWWWWWDD',
      'DDWWWWWWWWDDWWWWWWWWWWDD',
      'DDWWWWWWWWDDDWWWWWWWWWDD',
      'DDWWWWWWWWDDDDDDWWWWWWDD',
      'DDWWWWWWWWWDDDDDWWWWWWDD',
      'DDWWWWWWWWWWWWWWWWWWWWDD',
      'DDWWWWWWWWWWWWWWWWWWWWDD',
      'DDWWWWWWWWWWWWWWWWWWWWDD',
      '.DDWWWWWWWWWWWWWWWWWWDD.',
      '.DDWWWWWWWWWWWWWWWWWWDD.',
      '...DDWWWWWWWWWWWWWWDD...',
      '...DDWWWWWWWWWWWWWWDD...',
      '.....DDWWWWWWWWWWDD.....',
      '.....DDDDDDDDDDDDDD.....',
      '......DDDDDDDDDDDD......',
      '......DDD......DDD......',
      '......DD........DD......',
    ],
    legend: { W: WHITE, D: DARK },
  },
  {
    name: 'Sun',
    // 26x26, 560 tiles, 3 colors
    rows: [
      '.........DDDDDDDD.........',
      '.......DDDDDDDDDDDD.......',
      '.....DDDDOOOOOOOODDDD.....',
      '...DDDDOOOOOOOOOOOODDDD...',
      '...DDOOOOOOOOOOOOOOOODD...',
      '.DDOOOOOOOOOOOOOOOOOOOODD.',
      '.DDOOOOOODDDDDDDDOOOOOODD.',
      'DDOOOOODDDDDDDDDDDDOOOOODD',
      'DDOOOOODDYYYYYYYYDDOOOOODD',
      'DDOOOODDYYYYYYYYYYDDOOOODD',
      'DDOOOODDYYYYYYYYYYDDOOOODD',
      'DDOOOODDYYYYYYYYYYDDOOOODD',
      'DDOOOODDYYYYYYYYYYDDOOOODD',
      'DDOOOODDYYYYYYYYYYDDOOOODD',
      'DDOOOODDYYYYYYYYYYDDOOOODD',
      'DDOOOODDYYYYYYYYYYDDOOOODD',
      'DDOOOODDYYYYYYYYYYDDOOOODD',
      'DDOOOOODDYYYYYYYYDDOOOOODD',
      'DDOOOOODDDDDDDDDDDDOOOOODD',
      '.DDOOOOOODDDDDDDDOOOOOODD.',
      '.DDOOOOOOOOOOOOOOOOOOOODD.',
      '...DDOOOOOOOOOOOOOOOODD...',
      '...DDDDOOOOOOOOOOOODDDD...',
      '.....DDDDOOOOOOOODDDD.....',
      '.......DDDDDDDDDDDD.......',
      '.........DDDDDDDD.........',
    ],
    legend: { Y: YELLOW, O: ORANGE, D: DARK },
  },
  {
    name: 'Camera',
    // 26x18, 420 tiles, 3 colors
    rows: [
      '.......DDDDDD.............',
      '.....DDDDDDDDDD...........',
      '.DDDDDDDDDDDDDDDDDDDDDD...',
      'DDDDDDDDDDDDDDDDDDDDDDDDD.',
      'DDDSSSSSSSSSSSSSSSSSSDDDD.',
      'DDSSSSSSSSSSSSSSSSSSSSSDDD',
      'DDSSSSSDDDDDDDDSSSSSSSSDDD',
      'DDSSSDDDDDDDDDDDDSSSSSSSDD',
      'DDSSSDDCCCCCCCCDDSSSSSSSDD',
      'DDSSDDCCCCCCCCCCDDSSSSSSDD',
      'DDSSDDCCCCCCCCCCDDSSSSSSDD',
      'DDSSSDDCCCCCCCCDDSSSSSSSDD',
      'DDSSSDDDDDDDDDDDDSSSSSSSDD',
      'DDSSSSSDDDDDDDDSSSSSSSSDDD',
      'DDSSSSSSSSSSSSSSSSSSSSSDDD',
      'DDDSSSSSSSSSSSSSSSSSSDDDD.',
      'DDDDDDDDDDDDDDDDDDDDDDDDD.',
      '.DDDDDDDDDDDDDDDDDDDDDD...',
    ],
    legend: { C: CYAN, D: DARK, S: SLATE },
  },
  {
    name: 'Tomato',
    // 22x24, 352 tiles, 3 colors
    rows: [
      '.........DD...........',
      '.......DDDDD..........',
      '.......DGGDD..........',
      '.....DDDGGDDD.........',
      '.....DDDGGDDDDD.......',
      '...DDDDGGGGDDDDDD.....',
      '..DDGGGGGGGGGGGGD.....',
      '..DDGGGGGGGGGGGGDD....',
      '....DDDDDDDDDDDDDD....',
      '....DDDDDDDDDDDDDDD...',
      '...DDRRRRRRRRRRRRDD...',
      '.DDRRRRRRRRRRRRRRRRDD.',
      '.DDRRRRRRRRRRRRRRRRDD.',
      'DDRRRRRRRRRRRRRRRRRRDD',
      'DDRRRRRRRRRRRRRRRRRRDD',
      'DDRRRRRRRRRRRRRRRRRRDD',
      'DDRRRRRRRRRRRRRRRRRRDD',
      '.DDRRRRRRRRRRRRRRRRDD.',
      '.DDRRRRRRRRRRRRRRRRDD.',
      '...DDRRRRRRRRRRRRDD...',
      '...DDRRRRRRRRRRRRDD...',
      '.....DDRRRRRRRRDD.....',
      '.....DDDDDDDDDDDD.....',
      '.......DDDDDDDD.......',
    ],
    legend: { R: RED, G: GREEN, D: DARK },
  },
  {
    name: 'Pear',
    // 22x28, 352 tiles, 3 colors
    rows: [
      '.........DD...........',
      '........DDDDD.........',
      '........DDTTD.........',
      '.......DDDTTDDD.......',
      '.......DDDTTDDD.......',
      '.....DDDDDTTDDDDD.....',
      '....DDGGGGDDGGGGDD....',
      '....DDGGGGDDGGGGDD....',
      '.....DDDDDDDDDDDD.....',
      '.......DDDDDDDD.......',
      '........DDGGDD........',
      '........DGGGGD........',
      '.......DDGGGGDD.......',
      '......DDGGGGGGDD......',
      '......DDGGGGGGDD......',
      '.....DDGGGGGGGGDD.....',
      '.....DDGGGGGGGGDD.....',
      '...DDGGGGGGGGGGGGDD...',
      '...DDGGGGGGGGGGGGDD...',
      '.DDGGGGGGGGGGGGGGGGDD.',
      '.DDGGGGGGGGGGGGGGGGDD.',
      'DDGGGGGGGGGGGGGGGGGGDD',
      'DDGGGGGGGGGGGGGGGGGGDD',
      '.DDGGGGGGGGGGGGGGGGDD.',
      '.DDGGGGGGGGGGGGGGGGDD.',
      '...DDGGGGGGGGGGGGDD...',
      '...DDDDDDDDDDDDDDDD...',
      '.....DDDDDDDDDDDD.....',
    ],
    legend: { G: GREEN, D: DARK, T: TAN },
  },
  {
    name: 'Mushroom',
    // 26x24, 412 tiles, 3 colors
    rows: [
      '.......DDDDDDDDDD.........',
      '.....DDDDDDDDDDDDDD.......',
      '.....DDRRRRRRRRRRDD.......',
      '...DDRRRRRRRRRRRRRRDD.....',
      '...DDRRRWWRRRRRRRRRDD.....',
      '.DDRRRRRWWRRRRRRRRRRRDD...',
      '.DDRRRRRRRRRRRWWRRRRRDD...',
      'DDRRRRRRRRRRRRWWRRRRRRDD..',
      'DDRRWWRRRRRRRRRRRRRRRRDD..',
      'DDRRWWRRRRRRRRRRRRRRRRDD..',
      'DDRRRRRRRRRRWWRRRRRRRRDD..',
      '.DDRRRRRRRRRWWRRRRRRRDD...',
      '.DDDDDDDDDDDDDDDDDDDDDD...',
      '...DDDDDDDDDDDDDDDDDD.....',
      '.....DDDDWWWWWWDDDD.......',
      '......DDWWWWWWWWDD........',
      '......DDWWWWWWWWDD........',
      '......DDWWWWWWWWDD........',
      '......DDWWWWWWWWDD........',
      '.....DDDWWWWWWWWDDD.......',
      '.....DDDWWWWWWWWDDD.......',
      '....DDDDDWWWWWWDDDDD......',
      '....DDDDDDDDDDDDDDDD......',
      '.....DDDDDDDDDDDDDD.......',
    ],
    legend: { R: RED, W: WHITE, D: DARK },
  },
  {
    name: 'Icecream',
    // 18x28, 360 tiles, 4 colors
    rows: [
      '.....DDDDDDDD.....',
      '...DDDDDDDDDDDD...',
      '...DDMMMMMMMMDD...',
      '.DDMMMMMMMMMMMMDD.',
      '.DDMMMMMMMMMMMMDD.',
      'DDMMMMMMMMMMMMMMDD',
      'DDMMMMMMMMMMMMMMDD',
      '.DDMMMMMMMMMMMMDD.',
      '.DDMMMMMMMMMMMMDD.',
      '..DDMMMMMMMMMMDD..',
      '..DDWWWWWWWWWWDD..',
      '.DDWWWWWWWWWWWWDD.',
      '.DDWWWWWWWWWWWWDD.',
      'DDWWWWWWWWWWWWWWDD',
      'DDWWWWWWWWWWWWWWDD',
      '.DDWWWWWWWWWWWWDD.',
      '.DDWWWWWWWWWWWWDD.',
      '..DDWWWWWWWWWWDD..',
      '..DDTTTTTTTTTTDD..',
      '...DDTTTTTTTTDD...',
      '...DDTTTTTTTTDD...',
      '....DDTTTTTTDD....',
      '....DDTTTTTTDD....',
      '.....DDTTTTDD.....',
      '.....DDTTTTDD.....',
      '......DDTTD.......',
      '......DDDDD.......',
      '.......DD.........',
    ],
    legend: { M: MAGENTA, W: WHITE, D: DARK, T: TAN },
  },
  {
    name: 'Trophy',
    // 22x28, 492 tiles, 3 colors
    rows: [
      '...DDDDDDDDDDDDDDDD...',
      '..DDDDDDDDDDDDDDDDDD..',
      '..DDDYYYYYYYYYYYYDDD..',
      '.DDDYYYYYYYYYYYYYYDDD.',
      '.DDDYYYYYYYYYYYYYYDDD.',
      'DDDDDYYYYYYYYYYYYDDDDD',
      'DDSSDYYYYYYYYYYYYDSSDD',
      'DDSSDDYYYYYYYYYYDDSSDD',
      'DDSSDDYYYYYYYYYYDDSSDD',
      'DDSSDDDYYYYYYYYDDDSSDD',
      'DDSSDDDYYYYYYYYDDDSSDD',
      'DDSSSDDDYYYYYYDDDSSSDD',
      'DDSSSSDDYYYYYYDDSSSSDD',
      '.DDSSSDDYYYYYYDDSSSDD.',
      '.DDDDDDDYYYYYYDDDDDDD.',
      '...DDDDDYYYYYYDDDDD...',
      '.....DDDYYYYYYDDD.....',
      '......DDYYYYYYDD......',
      '......DDYYYYYYDD......',
      '.....DDDYYYYYYDDD.....',
      '.....DDDYYYYYYDDD.....',
      '....DDDYYYYYYYYDDD....',
      '....DDDYYYYYYYYDDD....',
      '...DDYYYYYYYYYYYYDD...',
      '...DYYYYYYYYYYYYYYD...',
      '..DDYYYYYYYYYYYYYYDD..',
      '..DDDDDDDDDDDDDDDDDD..',
      '...DDDDDDDDDDDDDDDD...',
    ],
    legend: { Y: YELLOW, D: DARK, S: SLATE },
  },
  {
    name: 'Crab',
    // 26x18, 372 tiles, 2 colors
    rows: [
      '...DD................DD...',
      '.DDDDDD............DDDDDD.',
      '.DDRRDD............DDRRDD.',
      'DDRRRRDDD........DDDRRRRDD',
      'DDRRRRDDDDDDDDDDDDDDRRRRDD',
      '.DDRRDRDDDDDDDDDDDDRDRRDD.',
      '..DDDDDRRRRRRRRRRRRDDDDD..',
      '..DDDDRRRRRRRRRRRRRRDDDD..',
      '.DDRRRRRDDRRRRRRDDRRRRRDD.',
      'DDRRRRRRDDRRRRRRDDRRRRRRDD',
      'DDRRRRRRRRRRRRRRRRRRRRRRDD',
      'DDRRRRRRRRRRRRRRRRRRRRRRDD',
      'DDRRRRRRRRRRRRRRRRRRRRRRDD',
      '.DDRRRRRRRRRRRRRRRRRRRRDD.',
      '.DDRRRRRRRRRRRRRRRRRRRRDD.',
      '...DDRRRRRRRRRRRRRRRRDD...',
      '...DDDDDDDDDDDDDDDDDDDD...',
      '.....DDDDDDDDDDDDDDDD.....',
    ],
    legend: { R: RED, D: DARK },
  },
  {
    name: 'Penguin',
    // 22x26, 434 tiles, 3 colors
    rows: [
      '.......DDDDDDDD.......',
      '.....DDDDDDDDDDDD.....',
      '.....DDDDDDDDDDDD.....',
      '...DDDDDDDDDDDDDDDD...',
      '...DDDWWWDDDDWWWDDD...',
      '..DDDDWWWWDDWWWWDDDD..',
      '..DDDDDWWWDDWWWDDDDD..',
      '..DDDDDDWWDDWWDDDDDD..',
      '..DDDDDDDDOODDDDDDDD..',
      '.DDDDDDDDDOODDDDDDDDD.',
      '.DDDDDDDDWWWWDDDDDDDD.',
      'DDDDDDDDWWWWWWDDDDDDDD',
      'DDDDDDDDWWWWWWDDDDDDDD',
      'DDDDDDDDWWWWWWDDDDDDDD',
      'DDDDDDDDWWWWWWDDDDDDDD',
      '.DDDDDDDWWWWWWDDDDDDD.',
      '.DDDDDDDWWWWWWDDDDDDD.',
      '..DDDDDDWWWWWWDDDDDD..',
      '..DDDDDDWWWWWWDDDDDD..',
      '...DDDDDWWWWWWDDDDD...',
      '...DDDDDWWWWWWDDDDD...',
      '....DDDDDWWWWDDDDD....',
      '....DDDDDDDDDDDDDD....',
      '....DDDDDDDDDDDDDD....',
      '....DDOODD..DDOODD....',
      '.....DOOD....DOOD.....',
    ],
    legend: { O: ORANGE, W: WHITE, D: DARK },
  },
  {
    name: 'Strawberry',
    // 22x24, 372 tiles, 4 colors
    rows: [
      '.......DDDDDDDD.......',
      '.....DDDDDDDDDDDD.....',
      '.....DGGGGGGGGGGD.....',
      '...DDGGGGGGGGGGGGDD...',
      '..DDGGDDGGGGGGDDGGDD..',
      '..DDGGDDDGGGGDDDGGDD..',
      '....DDDDDDDDDDDDDD....',
      '....DDDDDDDDDDDDDD....',
      '...DDRRRRRRRRRRRRDD...',
      '.DDRRRRRRRRRRRRRRRRDD.',
      '.DDRWWRRRRRRWWRRRRRDD.',
      'DDRRWWRRRRRRWWRRRRRRDD',
      'DDRRRRRRRRRRRRRRWWRRDD',
      'DDRRRRRRRRRRRRRRWWRRDD',
      'DDRRRRWWRRRRRRRRRRRRDD',
      '.DDRRRWWRRRRRRRRRRRDD.',
      '.DDRRRRRRRRRWWRRRRRDD.',
      '...DDRRRRRRRWWRRRDD...',
      '...DDRRRRRRRRRRRRDD...',
      '.....DDRRRRRRRRDD.....',
      '.....DDRRRRRRRRDD.....',
      '.......DDRRRRDD.......',
      '.......DDDDDDDD.......',
      '.........DDDD.........',
    ],
    legend: { R: RED, G: GREEN, W: WHITE, D: DARK },
  },
  {
    name: 'Watermelon',
    // 26x18, 360 tiles, 4 colors
    rows: [
      '.DDDDDDDDDDDDDDDDDDDDDDDD.',
      'DDDDDDDDDDDDDDDDDDDDDDDDDD',
      'DDGGGGGGGGGGGGGGGGGGGGGGDD',
      'DDGGGGGGGGGGGGGGGGGGGGGGDD',
      'DDDDWWWWWWWWWWWWWWWWWWDDDD',
      '.DDDWWWWWWWWWWWWWWWWWWDDD.',
      '.DDDRRRRRRRRRRRRRRRRRRDDD.',
      '..DDRRRRRRRRRRRRRRRRRRDD..',
      '..DDRRRRDDRRRRRRDDRRRRDD..',
      '...DDRRRDDRRRRRRDDRRRDD...',
      '...DDRRRRRRRRRRRRRRRRDD...',
      '....DDRRRRRRRRRRRRRRDD....',
      '....DDRRRRDDRRRRDDRRDD....',
      '.....DDRRRDDRRRRDDRRD.....',
      '.....DDRRRRRRRRRRRRDD.....',
      '.......DDRRRRRRRRRD.......',
      '.......DDDDDDDDDDDD.......',
      '.........DDDDDDDD.........',
    ],
    legend: { R: RED, G: GREEN, W: WHITE, D: DARK },
  },
  {
    name: 'Book',
    // 24x18, 420 tiles, 3 colors
    rows: [
      '...DDDDDDDDDDDDDDDDDD...',
      '.DDDDDDDDDDDDDDDDDDDDDD.',
      '.DDWWWWWWDDDDDDWWWWWWDD.',
      'DDWWWWWWWWDDDDWWWWWWWWDD',
      'DDWWWWWWWWDDDDWWWWWWWWDD',
      'DDWWWWWWWWDDDDWWWWWWWWDD',
      'DDWWWWWWWWDDDDWWWWWWWWDD',
      'DDWWWWWWWWDDDDWWWWWWWWDD',
      'DDWWWWWWWWDDDDWWWWWWWWDD',
      'DDWWWWWWWWDDDDWWWWWWWWDD',
      'DDWWWWWWWWDDDDWWWWWWWWDD',
      'DDWWWWWWWWDDDDWWWWWWWWDD',
      'DDRRRRRRRRDDDDRRRRRRRRDD',
      'DDRRRRRRRRDDDDRRRRRRRRDD',
      'DDRRRRRRRRDDDDRRRRRRRRDD',
      'DDDRRRRRRDDDDDDRRRRRRDDD',
      'DDDDDDDDDDDDDDDDDDDDDDDD',
      '.DDDDDDDDDDDDDDDDDDDDDD.',
    ],
    legend: { R: RED, W: WHITE, D: DARK },
  },
  {
    name: 'Envelope',
    // 26x18, 464 tiles, 3 colors
    rows: [
      '.DDDDDDDDDDDDDDDDDDDDDDDD.',
      'DDDDDDDDDDDDDDDDDDDDDDDDDD',
      'DDDWWWWWWWWWWWWWWWWWWWWDDD',
      'DDWWWWWWWWWWWWWWWWWWWWWWDD',
      'DDWWDDWWWWWWWWWWWWWWDDWWDD',
      'DDWWDDDWWWWWWWWWWWWDDDWWDD',
      'DDWWWDDDWWWWWWWWWWDDDWWWDD',
      'DDWWWWDDDWWWWWWWWDDDWWWWDD',
      'DDWWWWWDDDWWWWWWDDDWWWWWDD',
      'DDWWWWWWDDDWWWWDDDWWWWWWDD',
      'DDWWWWWWWDWDMMDWDWWWWWWWDD',
      'DDWWWWWWWWDMMMMDWWWWWWWWDD',
      'DDWWWWWWWWMMMMMMWWWWWWWWDD',
      'DDWWWWWWWWWMMMMWWWWWWWWWDD',
      'DDWWWWWWWWWMMMMWWWWWWWWWDD',
      'DDDWWWWWWWWWMMWWWWWWWWWDDD',
      'DDDDDDDDDDDDDDDDDDDDDDDDDD',
      '.DDDDDDDDDDDDDDDDDDDDDDDD.',
    ],
    legend: { M: MAGENTA, W: WHITE, D: DARK },
  },
  {
    name: 'Sheep',
    // 26x22, 488 tiles, 3 colors
    rows: [
      '.....DDDDDDDDDDDDDDDD.....',
      '...DDDDDDDDDDDDDDDDDDDD...',
      '...DDWWWWWWWWWWWWWWWWDD...',
      '.DDWWWWWWWWWWWWWWWWWWWWDD.',
      '.DDWWWWWWWWWWWWWWWWWWWWDD.',
      'DDWWWWWWWWWWWWWWWWWWWWWWDD',
      'DDWWWWWWWWWWWWWWWWWWWWWWDD',
      'DDWWWWWWWWWWWWWWWWWWWWWWDD',
      'DDWWWWWWWWWWWWWWWWWWWWWWDD',
      '.DDWWWWWWWWWWWWWWWWWWWWDD.',
      '.DDWWWWWWWWWWWWWWWWWWWWDD.',
      '..DDDWWWWWWWWWWWWWWWWDDD..',
      '..DDDDDDDDSSSSSSDDDDDDDD..',
      '.DDDDDDDDSSSSSSSSDDDDDDDD.',
      '.DDSSDDDDSSSSSSSSDDDDSSDD.',
      'DDSSSSDDSSSSSSSSSSDDSSSSDD',
      'DDSSSSDDSSDDSSDDSSDDSSSSDD',
      '.DDSSDDDSSDDSSDDSSDDDSSDD.',
      '.DDDDDDDSSSSSSSSSSDDDDDDD.',
      '...DDDDDDSSSSSSSSDDDDDD...',
      '.......DDDDDDDDDDDD.......',
      '.........DDDDDDDD.........',
    ],
    legend: { W: WHITE, D: DARK, S: SLATE },
  },
  {
    name: 'Cupcake',
    // 22x24, 432 tiles, 3 colors
    rows: [
      '.......DDDDDDDD.......',
      '.....DDDDDDDDDDDD.....',
      '.....DDMMMMMMMMDD.....',
      '...DDMMMMMMMMMMMMDD...',
      '...DDMMMMMMMMMMMMDD...',
      '.DDMMMMMMMMMMMMMMMMDD.',
      '.DDMMMMMMMMMMMMMMMMDD.',
      'DDMMMMMMMMMMMMMMMMMMDD',
      'DDMMMMMMMMMMMMMMMMMMDD',
      '.DDMMMMMMMMMMMMMMMMDD.',
      '..DMMMMMMMMMMMMMMMMD..',
      '..DDDMMMMMMMMMMMMDDD..',
      '.DDDDDDDDDDDDDDDDDDDD.',
      'DDDDDDDDDDDDDDDDDDDDDD',
      'DDDBBDDDDBBDDDDBBBBDDD',
      'DDBBBBDDBBBBDDBBBBBBDD',
      'DDBBBBDDBBBBDDBBBBBBDD',
      '.DDBBBDDBBBBDDBBBBBDD.',
      '.DDBBBDDBBBBDDBBBBBDD.',
      '..DDBBDDBBBBDDBBBBDD..',
      '..DDBBBBBBBBBBBBBBDD..',
      '...DDBBBBBBBBBBBBDD...',
      '...DDDDDDDDDDDDDDDD...',
      '.....DDDDDDDDDDDD.....',
    ],
    legend: { B: BLUE, M: MAGENTA, D: DARK },
  },
  {
    name: 'Donut',
    // 24x22, 396 tiles, 4 colors
    rows: [
      '.......DDDDDDDDDD.......',
      '.....DDDDDDDDDDDDDD.....',
      '.....DDMMMMMMMMMMDD.....',
      '...DDMMMMMMMMMMMMMMDD...',
      '...DDMWWMMMMMMWWMMMDD...',
      '.DDMMMWWMMMMMMWWMMMMMDD.',
      '.DDMMMMMMDDDDDDDMMMMMDD.',
      'DDMMMMMDDDDDDDDDDMMMMMDD',
      'DDMMMMMDDDD..DDDDMMMMMDD',
      'DDMMMMDDD......DDDMMMMDD',
      'DDMMMMDD........DDMMMMDD',
      'DDMMMMDD........DDMMMMDD',
      'DDMMMTDDD......DDDTMMMDD',
      'DDMTTTTDDDD..DDDDTTTTMDD',
      'DDTTTTTDDDDDDDDDDTTTTTDD',
      '.DDTTTTTTDDDDDDTTTTTTDD.',
      '.DDTTTTTTTTTTTTTTTTTTDD.',
      '...DDTTTTTTTTTTTTTTDD...',
      '...DDTTTTTTTTTTTTTTDD...',
      '.....DDTTTTTTTTTTDD.....',
      '.....DDDDDDDDDDDDDD.....',
      '.......DDDDDDDDDD.......',
    ],
    legend: { M: MAGENTA, W: WHITE, D: DARK, T: TAN },
  },
  {
    name: 'Pineapple',
    // 22x28, 424 tiles, 3 colors
    rows: [
      '.........DDDD.........',
      '.......DDDDDDDD.......',
      '.......DGGDDGGD.......',
      '.....DDGGGDDGGGDD.....',
      '.....DGGDDGGDDGGD.....',
      '....DDGGDDGGDDGGDD....',
      '....DDDGGGDDGGGDDD....',
      '.....DDDGGDDGGDDD.....',
      '......DDDDDDDDDD......',
      '......DDDDDDDDDD......',
      '.....DYYYYYYYYYYD.....',
      '...DDYYYYYYYYYYYYDD...',
      '...DYYDDYYDDYYDDYYD...',
      '.DDYYYDDYYDDYYDDYYYDD.',
      '.DYYDDYYDDYYDDYYDDYYD.',
      'DDYYDDYYDDYYDDYYDDYYDD',
      'DDYYDDYYDDYYDDYYDDYYDD',
      'DDYYDDYYDDYYDDYYDDYYDD',
      'DDYYDDYYDDYYDDYYDDYYDD',
      'DDYYDDYYDDYYDDYYDDYYDD',
      'DDYYDDYYDDYYDDYYDDYYDD',
      '.DYYDDYYDDYYDDYYDDYYD.',
      '.DDYYYDDYYDDYYDDYYYDD.',
      '...DYYDDYYDDYYDDYYD...',
      '...DDYYYYYYYYYYYYDD...',
      '.....DYYYYYYYYYYD.....',
      '.....DDDDDDDDDDDD.....',
      '.......DDDDDDDD.......',
    ],
    legend: { Y: YELLOW, G: GREEN, D: DARK },
  },
  {
    name: 'Cow',
    // 26x20, 424 tiles, 3 colors
    rows: [
      '...DD................DD...',
      '.DDDDDD............DDDDDD.',
      '.DDWWDD............DDWWDD.',
      'DDWWWWDDD........DDDWWWWDD',
      'DDWWWWDDDDDDDDDDDDDDWWWWDD',
      '.DDWWDWDDDDDDDDDDDDWDWWDD.',
      '..DDDDDWWWWWWWWWWWWDDDDD..',
      '..DDDDWWWWWWWWWWWWWWDDDD..',
      '.DDDDWWWDDWWWWWWDDWWWDDDD.',
      'DDDWWWWWDDWWWWWWDDWWWWWDDD',
      'DDDWWWWWWWWWWWWWWWWWWWWDDD',
      'DDWWWWWWWWWWWWWWWWWWWWWWDD',
      'DDWWWWWWWWWWWWWWWWWWWWWWDD',
      'DDWWWWWWWWWWWWWWWWWWWWWWDD',
      'DDWWWWWDMMMMMMMMMMMMDWWWDD',
      '.DDWWDDDMMMMMMMMMMMMDDWWD.',
      '.DDDDDDDMMDDMMMMDDMMDDDDD.',
      '...DDDDDMMDDDMMDDDMMDDD...',
      '...DDDDDDDDDDDDDDDDDDDD...',
      '.....DDDDDDDDDDDDDDDD.....',
    ],
    legend: { M: MAGENTA, W: WHITE, D: DARK },
  },
  {
    name: 'Rocket',
    // 24x32, 408 tiles, 6 colors
    rows: [
      '...........DD...........',
      '.........DDDDDD.........',
      '.........DDWWDD.........',
      '.......DDWWWWWWDD.......',
      '.......DDWWWWWWDD.......',
      '......DDWWWWWWWWDD......',
      '......DDWWWCCWWWDD......',
      '......DDWWCCCCWWDD......',
      '......DDWWCCCCWWDD......',
      '......DDWWWCCWWWDD......',
      '......DDWWWWWWWWDD......',
      '.....DDWWWWWWWWWWDD.....',
      '.....DDWWWWWWWWWWDD.....',
      '...DDDWWWWWWWWWWWWDDD...',
      '...DDMWWWWWWWWWWWWMDD...',
      '.DDMMMWWWWWWWWWWWWMMMDD.',
      '.DDMMMWWWWWWWWWWWWMMMDD.',
      'DDMMMMWWWWWWWWWWWWMMMMDD',
      'DDMMMMDWWWWWWWWWWDMMMMDD',
      '.DDMMDDDWWWWWWWWDDDMMDD.',
      '.DDDDDDDWWWWWWWWDDDDDDD.',
      '...DDDDDDWWWWWWDDDDDD...',
      '........DDOOOODD........',
      '........DOOOOOOD........',
      '.......DDOOOOOODD.......',
      '......DDOOOOOOOODD......',
      '......DDOOYYYYOODD......',
      '.......DDOYYYYODD.......',
      '.......DDOOOOOODD.......',
      '.........DDOODD.........',
      '.........DDDDDD.........',
      '...........DD...........',
    ],
    legend: { Y: YELLOW, C: CYAN, O: ORANGE, M: MAGENTA, W: WHITE, D: DARK },
  },
  {
    name: 'Cherry',
    // 22x28, 374 tiles, 3 colors
    rows: [
      '.............DDDDDD...',
      '...........DDDDDDDDD..',
      '...........DDGGGGGDD..',
      '.........DDDGGGGGGD...',
      '.....DDDDDDDGGGGGDD...',
      '...DDDDDDDDDGGGDD.....',
      '...DDGGGGDDDGGGDD.....',
      '..DDGGGGGGDDGGDD......',
      '..DDGGGGGGGGGDDD......',
      '...DDGGGGGGGDDD.......',
      '...DDDDDDDDDDDD.......',
      '.....DDDDDDDDD........',
      '........DDDDDD........',
      '........DDDDDDD.......',
      '.....DDDDRRRRDDDD.....',
      '...DDDDRRRRRRRRDDDD...',
      '...DDRRRRRRRRRRRRDD...',
      '.DDRRRRRRRRRRRRRRRRDD.',
      '.DDRRRRRRRRRRRRRRRRDD.',
      'DDRRRRRRRRRRRRRRRRRRDD',
      'DDRRRRRRRRRRRRRRRRRRDD',
      '.DDRRRRRRRRRRRRRRRRDD.',
      '.DDRRRRRRRRRRRRRRRRDD.',
      '...DDRRRRRRRRRRRRDD...',
      '...DDDDRRRRRRRRDDDD...',
      '.....DDDDRRRRDDDD.....',
      '.......DDDDDDDD.......',
      '.........DDDD.........',
    ],
    legend: { R: RED, G: GREEN, D: DARK },
  },
  {
    name: 'Lighthouse',
    // 22x26, 400 tiles, 4 colors
    rows: [
      '.........DDDD.........',
      '.......DDDDDDDD.......',
      '.......DYYYYYYD.......',
      '......DDYYYYYYDD......',
      '......DDDDDDDDDD......',
      '.....DDDDDDDDDDDD.....',
      '.....DDDDDDDDDDDD.....',
      '....DDDDDDDDDDDDDD....',
      '....DDDWWWWWWWWDDD....',
      '....DDWWWWWWWWWWDD....',
      '....DDRRRRRRRRRRDD....',
      '....DDRRRRRRRRRRDD....',
      '....DDWWWWWWWWWWDD....',
      '...DDDWWWWWWWWWWDDD...',
      '...DDRRRRRRRRRRRRDD...',
      '..DDRRRRRRRRRRRRRRDD..',
      '..DDWWWWWWWWWWWWWWDD..',
      '..DDWWWWWWWWWWWWWWDD..',
      '..DDRRRRRRRRRRRRRRDD..',
      '.DDDRRRRRRRRRRRRRRDDD.',
      '.DDWWWWWWWWWWWWWWWWDD.',
      'DDWWWWWWWWWWWWWWWWWWDD',
      'DDRRRRRRRRRRRRRRRRRRDD',
      'DDDRRRRRRRRRRRRRRRRDDD',
      'DDDDDDDDDDDDDDDDDDDDDD',
      '.DDDDDDDDDDDDDDDDDDDD.',
    ],
    legend: { R: RED, Y: YELLOW, W: WHITE, D: DARK },
  },
  {
    name: 'Present',
    // 24x24, 496 tiles, 3 colors
    rows: [
      '.....DD..........DD.....',
      '...DDDDDD......DDDDDD...',
      '...DDYYDD......DDYYDD...',
      '..DDYYYYYDD..DDYYYYYDD..',
      '..DDYYYYYDDDDDDYYYYYDD..',
      '...DDYYYYYYDDYYYYYYDD...',
      '....DDDYYYYYYYYYYDDD....',
      '....DDDDYYYYYYYYDDDD....',
      '.DDDDDDDYYYYYYYYDDDDDDD.',
      'DDDDDDDDDYYYYYYDDDDDDDDD',
      'DDDRRRRDDYYYYYYDDRRRRDDD',
      'DDRRRRRRDDYYYYDDRRRRRRDD',
      'DDRRRRRRDDYYYYDDRRRRRRDD',
      'DDDRRRRDDDYYYYDDDRRRRDDD',
      'DDDDDDDDDDYYYYDDDDDDDDDD',
      'DDDDDDDDDDYYYYDDDDDDDDDD',
      'DDDRRRRDDDYYYYDDDRRRRDDD',
      'DDRRRRRRDDYYYYDDRRRRRRDD',
      'DDRRRRRRDDYYYYDDRRRRRRDD',
      'DDRRRRRRDDYYYYDDRRRRRRDD',
      'DDRRRRRRDDYYYYDDRRRRRRDD',
      'DDDRRRRDDDDYYDDDDRRRRDDD',
      'DDDDDDDDDDDDDDDDDDDDDDDD',
      '.DDDDDDDDDDDDDDDDDDDDDD.',
    ],
    legend: { R: RED, Y: YELLOW, D: DARK },
  },
  {
    name: 'Butterfly',
    // 34x30, 662 tiles, 4 colors
    rows: [
      '.....DDDD................DDDD.....',
      '...DDDDDDDD............DDDDDDDD...',
      '...DDMMMMDDDD........DDDDMMMMDD...',
      '.DDMMMMMMMMDDDD....DDDDMMMMMMMMDD.',
      '.DDMMMMMMMMMMDD....DDMMMMMMMMMMDD.',
      'DDMMMMMMMMMMMMMD..DMMMMMMMMMMMMMDD',
      'DDMMMMMPPMMMMMMDDDDMMMMMMPPMMMMMDD',
      'DDMMMMPPPPMMMMMMDDMMMMMMPPPPMMMMDD',
      'DDMMMMPPPPMMMMMMDDMMMMMMPPPPMMMMDD',
      'DDMMMMMPPMMMMMMMDDMMMMMMMPPMMMMMDD',
      'DDMMMMMMMMMMMMMMDDMMMMMMMMMMMMMMDD',
      '.DDMMMMMMMMMMMMMDDMMMMMMMMMMMMMDD.',
      '.DDMMMMMMMMMMMMMDDMMMMMMMMMMMMMDD.',
      '...DDMMMMMMMMMMMDDMMMMMMMMMMMDD...',
      '...DDDDMMMMMMMMMDDMMMMMMMMMDDDD...',
      '.....DDDDMMMMMMMDDMMMMMMMDDDD.....',
      '........DMMMMMMMDDMMMMMMMD........',
      '........DDMMMMMMDDMMMMMMDD........',
      '.......DDCCMMMMMDDMMMMMCCDD.......',
      '......DDCCCCCMMMDDMMMCCCCCDD......',
      '......DDCCCCCMMMDDMMMCCCCCDD......',
      '.......DDCCCCCCMDDMCCCCCCDD.......',
      '.......DDCCCCCCCDDCCCCCCCDD.......',
      '.........DDCCCCCDDCCCCCDD.........',
      '.........DDCCCCCDDCCCCCDD.........',
      '...........DDCCDDDDCCDD...........',
      '...........DDDDDDDDDDDD...........',
      '.............DDDDDDDD.............',
      '.............DDDDDDDD.............',
      '...............DDDD...............',
    ],
    legend: { P: PURPLE, C: CYAN, M: MAGENTA, D: DARK },
  },
  {
    name: 'Snowman',
    // 22x28, 456 tiles, 3 colors
    rows: [
      '.......DDDDDDDD.......',
      '.....DDDDDDDDDDDD.....',
      '.....DDDDDDDDDDDD.....',
      '....DDDDDDDDDDDDDD....',
      '....DDWWWWWWWWWWDD....',
      '...DDWWWWWWWWWWWWDD...',
      '...DWWDDWWWWWWDDWWD...',
      '..DDWWDDWWWWWWDDWWDD..',
      '..DDWWWWWWOOWWWWWWDD..',
      '..DDWWWWWWOOWWWWWWDD..',
      '..DDWWWWDDDDDDWWWWDD..',
      '...DDWWWDDDDDDWWWDD...',
      '....DDWWWWWWWWWWDD....',
      '....DDWWWWWWWWWWDD....',
      '...DDWWWWWWWWWWWWDD...',
      '.DDWWWWWWWWWWWWWWWWDD.',
      '.DDWWWWWDDWWWWWWWWWDD.',
      'DDWWWWWWDDWWWWWWWWWWDD',
      'DDWWWWWWWWWWWWDDWWWWDD',
      'DDWWWWWWWWWWWWDDWWWWDD',
      'DDWWWWWWWWWWWWWWWWWWDD',
      '.DDWWWWWWWWWWWWWWWWDD.',
      '.DDWWWWWWWWWWWWWWWWDD.',
      '...DDWWWWWWWWWWWWDD...',
      '...DDWWWWWWWWWWWWDD...',
      '.....DDWWWWWWWWDD.....',
      '.....DDDDDDDDDDDD.....',
      '.......DDDDDDDD.......',
    ],
    legend: { O: ORANGE, W: WHITE, D: DARK },
  },
  {
    name: 'Burger',
    // 26x22, 488 tiles, 5 colors
    rows: [
      '.......DDDDDDDDDDDD.......',
      '.....DDDDDDDDDDDDDDDD.....',
      '.....DDYYYYYYYYYYYYDD.....',
      '...DDYYYYYYYYYYYYYYYYDD...',
      '...DDYYYWWYYYYWWYYYYYDD...',
      '.DDYYYYYWWYYYYWWYYYYYYYDD.',
      'DDYYYYYYYYYYYYYYYYYYYYYYDD',
      'DDYYYYYYYYYYYYYYYYYYYYYYDD',
      '..DDDDDDDDDDDDDDDDDDDDDD..',
      '..DDDDDDDDDDDDDDDDDDDDDD..',
      '.DDGGGGGGGGGGGGGGGGGGGGDD.',
      'DDGGGGGGGGGGGGGGGGGGGGGGDD',
      'DDRRRRRRRRRRRRRRRRRRRRRRDD',
      'DDDRRRRRRRRRRRRRRRRRRRRDDD',
      'DDDDDDDDDDDDDDDDDDDDDDDDDD',
      'DDDDDDDDDDDDDDDDDDDDDDDDDD',
      'DDYYYYYYYYYYYYYYYYYYYYYYDD',
      '.DYYYYYYYYYYYYYYYYYYYYYYD.',
      '.DDYYYYYYYYYYYYYYYYYYYYDD.',
      '...DDYYYYYYYYYYYYYYYYDD...',
      '...DDDDDDDDDDDDDDDDDDDD...',
      '.....DDDDDDDDDDDDDDDD.....',
    ],
    legend: { R: RED, Y: YELLOW, G: GREEN, W: WHITE, D: DARK },
  },
  {
    name: 'Drum',
    // 26x22, 508 tiles, 3 colors
    rows: [
      '.....DDDDDDDDDDDDDDDD.....',
      '...DDDDDDDDDDDDDDDDDDDD...',
      '...DDWWWWWWWWWWWWWWWWDD...',
      '.DDWWWWWWWWWWWWWWWWWWWWDD.',
      '.DWWWWWWWWWWWWWWWWWWWWWWD.',
      'DDWWWWWWWWWWWWWWWWWWWWWWDD',
      'DDDDDDDDDDDDDDDDDDDDDDDDDD',
      'DDDDDDDDDDDDDDDDDDDDDDDDDD',
      'DDDRRDDDRRRRRRRRRRDDDRRDDD',
      'DDRRRRDDRRRRRRRRRRDDRRRRDD',
      'DDRRRRRDDDRRRRRRDDDRRRRRDD',
      'DDRRRRRRDDDRRRRDDDRRRRRRDD',
      'DDRRRRRRRRDDRRDDRRRRRRRRDD',
      'DDRRRRRRRRDDRRDDRRRRRRRRDD',
      'DDRRRRRRDDDRRRRDDDRRRRRRDD',
      'DDRRRRRDDDRRRRRRDDDRRRRRDD',
      'DDRRRRDDRRRRRRRRRRDDRRRRDD',
      'DDDRRDDDRRRRRRRRRRDDDRRDDD',
      'DDDDDDDDDDDDDDDDDDDDDDDDDD',
      '.DDDDDDDDDDDDDDDDDDDDDDDD.',
      '.DDDDDD............DDDDDD.',
      '...DD................DD...',
    ],
    legend: { R: RED, W: WHITE, D: DARK },
  },
  {
    name: 'Frog',
    // 26x20, 408 tiles, 3 colors
    rows: [
      '...DDDD............DDDD...',
      '.DDDDDDDD........DDDDDDDD.',
      '.DDWWWWDD........DDWWWWDD.',
      'DDWWWWWWDD......DDWWWWWWDD',
      'DDWWDDWWDD......DDWWDDWWDD',
      'DDWWDDWWDDD....DDDWWDDWWDD',
      'DDWWWWWWDDDDDDDDDDWWWWWWDD',
      '.DDWWWWWDDDDDDDDDDWWWWWDD.',
      '..DDGGGGGGGGGGGGGGGGGGDD..',
      '..DGGGGGGGGGGGGGGGGGGGGD..',
      '.DDGGGGGGGGGGGGGGGGGGGGDD.',
      'DDGGGGGGGGGGGGGGGGGGGGGGDD',
      'DDGGGGGGGGGGGGGGGGGGGGGGDD',
      'DDGGGGGGGGGGGGGGGGGGGGGGDD',
      'DDGGGGGGGGGGGGGGGGGGGGGGDD',
      '.DDGGGGGGGGGGGGGGGGGGGGDD.',
      '.DDGGGGGGDDDDDDDDGGGGGGDD.',
      '...DDGGDDDDDDDDDDDDGGDD...',
      '...DDDDDD........DDDDDD...',
      '.....DD............DD.....',
    ],
    legend: { G: GREEN, W: WHITE, D: DARK },
  },
  {
    name: 'Panda',
    // 24x20, 408 tiles, 2 colors
    rows: [
      '...DDDD..........DDDD...',
      '.DDDDDDDD......DDDDDDDD.',
      '.DDDDDDDD......DDDDDDDD.',
      'DDDDDDDDDDD..DDDDDDDDDDD',
      'DDDDDDDDDDDDDDDDDDDDDDDD',
      '.DDDDDDDDDDDDDDDDDDDDDD.',
      '..DDDWWWWWWWWWWWWWWDDD..',
      '..DWWWWWWWWWWWWWWWWWWD..',
      '.DDWWWWWWWWWWWWWWWWWWDD.',
      'DDWWWWWWWWWWWWWWWWWWWWDD',
      'DDWWWDDWWWWWWWWWWDDWWWDD',
      'DDWWDDDDWWWWWWWWDDDDWWDD',
      'DDWWDDDDWWWWWWWWDDDDWWDD',
      'DDWWWDDWWWWWWWWWWDDWWWDD',
      'DDWWWWWWWWDDDDWWWWWWWWDD',
      '.DDWWWWWWWDDDDWWWWWWWDD.',
      '.DDWWWWWWWWWWWWWWWWWWDD.',
      '...DDWWWWWWWWWWWWWWDD...',
      '...DDDDDDDDDDDDDDDDDD...',
      '.....DDDDDDDDDDDDDD.....',
    ],
    legend: { W: WHITE, D: DARK },
  },
  {
    name: 'Pufferfish',
    // 26x22, 492 tiles, 2 colors
    rows: [
      '....DD..DD..DD..DD..DD....',
      '...DDD..DD..DD..DD..DDD...',
      '...DDDDDDDDDDDDDDDDDDDD...',
      '.DDDDDDDDDDDDDDDDDDDDDDDD.',
      '.DDDDYYYYYYYYYYYYYYYYDDDD.',
      'DDDYYYYYYYYYYYYYYYYYYYYDDD',
      'DDDYYYYYYYYYYYYYYYYYYYYDDD',
      'DDYYYYYYYYYYYYYYYYYYYYYYDD',
      'DDYYYYDDYYYYYYYYYYDDYYYYDD',
      'DDYYYYDDYYYYYYYYYYDDYYYYDD',
      'DDYYYYYYYYYYYYYYYYYYYYYYDD',
      'DDYYYYYYYYYYYYYYYYYYYYYYDD',
      'DDYYYYYYYYDDDDDDYYYYYYYYDD',
      'DDYYYYYYYYDDDDDDYYYYYYYYDD',
      'DDYYYYYYYYYYYYYYYYYYYYYYDD',
      'DDDYYYYYYYYYYYYYYYYYYYYDDD',
      'DDDYYYYYYYYYYYYYYYYYYYYDDD',
      '.DDDDYYYYYYYYYYYYYYYYDDDD.',
      '.DDDDDDDDDDDDDDDDDDDDDDDD.',
      '...DDDDDDDDDDDDDDDDDDDD...',
      '...DDD..DD..DD..DD..DDD...',
      '....DD..DD..DD..DD..DD....',
    ],
    legend: { Y: YELLOW, D: DARK },
  },
  {
    name: 'Cake',
    // 30x24, 482 tiles, 4 colors
    rows: [
      '......DD....DD....DD..........',
      '......DD....DD....DD..........',
      '......DD....DD....DD..........',
      '.....DDDD..DDDD..DDD..........',
      '.....DDDDDDDDDDDDDDD..........',
      '...DDDDDDDDDDDDDDDDDD.........',
      '...DDWWWWWWWWWWWWWWDD.........',
      '.DDDWWWWWWWWWWWWWWWWDDD.......',
      '.DDMMMMMMMMMMMMMMMMMMDD.......',
      'DDMMMMMMMMMMMMMMMMMMMMDD......',
      'DDMMMMMMMMMMMMMMMMMMMMDD......',
      'DDDMMMMMMMMMMMMMMMMMMDDD......',
      'DDDDDDDDDDDDDDDDDDDDDDDD......',
      'DDDDDDDDDDDDDDDDDDDDDDDD......',
      'DDDWWWWWWWWWWWWWWWWWWDDD......',
      'DDWWWWWWWWWWWWWWWWWWWWDD......',
      'DDWWWWWWWWWWWWWWWWWWWWDD......',
      'DDDWWWWWWWWWWWWWWWWWWDDD......',
      'DDDDDDDDDDDDDDDDDDDDDDDD......',
      'DDDDDDDDDDDDDDDDDDDDDDDD......',
      'DDCCCCCCCCCCCCCCCCCCCCDD......',
      'DDCCCCCCCCCCCCCCCCCCCCDD......',
      'DDDDDDDDDDDDDDDDDDDDDDDD......',
      '.DDDDDDDDDDDDDDDDDDDDDD.......',
    ],
    legend: { C: CYAN, M: MAGENTA, W: WHITE, D: DARK },
  },
  {
    name: 'Cat',
    // 28x26, 556 tiles, 4 colors
    rows: [
      '.....DD..............DD.....',
      '....DDDDD..........DDDDD....',
      '....DDGGD..........DGGDD....',
      '....DDGGGDD......DDGGGDD....',
      '....DDGGGDD......DDGGGDD....',
      '...DDDGGGGGDD..DDGGGGGDDD...',
      '...DDDGGGGGDDDDDDGGGGGDDD...',
      '..DDDGGGGGGGGDDGGGGGGGGDDD..',
      '..DDDGGGGGGGGGGGGGGGGGGDDD..',
      '.DDGGGGGGGGGGGGGGGGGGGGGGDD.',
      '.DDGGGGGDDGGGGGGGGDDGGGGGDD.',
      'DDGGGGGGDDGGGGGGGGDDGGGGGGDD',
      'DDGGGGGGDDGGGGGGGGDDGGGGGGDD',
      'DDGGGGGGDDGGGGGGGGDDGGGGGGDD',
      'DDGGGGGGGGGGGGGGGGGGGGGGGGDD',
      'DDGGGGGGGGGGGGGGGGGGGGGGGGDD',
      'DDGGGGGWWWWWMMMMWWWGGGGGGGDD',
      'DDGGGGWWWWWWWMMWWWWWGGGGGGDD',
      'DDGGGGWWWWWWWWWWWWWWGGGGGGDD',
      '.DDGGGGWWWWWWWWWWWWGGGGGGDD.',
      '.DDGGGGWWWWWWWWWWWWGGGGGGDD.',
      '...DDGGGGWWWWWWWWGGGGGGDD...',
      '...DDDDGGGGGGGGGGGGGGDDDD...',
      '.....DDDDGGGGGGGGGGDDDD.....',
      '.......DDDDDDDDDDDDDD.......',
      '.........DDDDDDDDDD.........',
    ],
    legend: { G: GREEN, M: MAGENTA, W: WHITE, D: DARK },
  },
  {
    name: 'Good dog',
    // 32x26, 532 tiles, 5 colors
    rows: [
      '.........DD..........DD.........',
      '.......DDDDDD......DDDDDD.......',
      '.......DDOODD......DDOODD.......',
      '......DDOOOODD....DDOOOODD......',
      '......DDOOTTDD....DDOOTTDD......',
      '.....DDDOOTTDDD..DDDOOTTDDD.....',
      '.....DDDOOOODDDDDDDDOOOODDD.....',
      '....DDDOOOOOODDDDDDOOOOOODDD....',
      '....DDDOOOOOOOOOOOOOOOOOODDD....',
      '....DDOOOOOOOOOOOOOOOOOOOODD....',
      '....DDOOOODDOOOOOOOODDOOOODD....',
      '....DDOOOODDOOOOOOOODDOOOODD....',
      '....DDOOOOOOOOOOOOOOOOOOOODD....',
      '....DDOOOOOOOOOOOOOOOOOOOODD....',
      '....DDOOOOOWWWWWWWWWWOOOOODD....',
      '....DDOOOWWWWWWWWWWWWWWOOODD....',
      '....DDOOOWWWDDDDDDDDWWWOOODD....',
      '....DDOOWWWWDDDDDDDDWWWWOODD....',
      '....DDOOWWWWWWMMMMWWWWWWOODD....',
      '....DDDOOWWWWWWMMWWWWWWOODDD....',
      '....DDDOOWWWWWWWWWWWWWWOODDD....',
      '.....DDDDOOWWWWWWWWWWOODDDD.....',
      '.....DDDDOOOOOOOOOOOOOODDDD.....',
      '.......DDDDOOOOOOOOOODDDD.......',
      '.......DDDDDDDDDDDDDDDDDD.......',
      '.........DDDDDDDDDDDDDD.........',
    ],
    legend: { O: ORANGE, M: MAGENTA, W: WHITE, D: DARK, T: TAN },
  },
  {
    name: 'House',
    // 30x26, 506 tiles, 5 colors
    rows: [
      '..............DD..............',
      '.............DDDD.............',
      '.............DRRD.............',
      '...........DDRRRRDD...........',
      '...........DDRRRRDD...........',
      '.........DDRRRRRRRRDD.........',
      '.........DDRRRRRRRRDD.........',
      '.......DDRRRRRRRRRRRRDD.......',
      '.......DDRRRRRRRRRRRRDD.......',
      '.....DDRRRRRRRRRRRRRRRRDD.....',
      '.....DRRRRRRRRRRRRRRRRRRD.....',
      '...DDDRRRRRRRRRRRRRRRRRRDDD...',
      '...DDDDDDDDDDDDDDDDDDDDDDDD...',
      '..DDDDDDDDDDDDDDDDDDDDDDDDDD..',
      '..DDDYYYYYYYYYYYYYYYYYYYYDDD..',
      '..DDYYYYYYYYYYYYYYYYYYYYYYDD..',
      '..DDYYYBBYYYYYYYYYYYYBBYYYDD..',
      '..DDYYBBBBYYYYYYYYYYBBBBYYDD..',
      '..DDYYBBBBYYYYYYYYYYBBBBYYDD..',
      '..DDYYYBBYYYYYYYYYYYYBBYYYDD..',
      '..DDYYYYYYYYYWWWWYYYYYYYYYDD..',
      '..DDYYYYYYYYWWWWWWYYYYYYYYDD..',
      '..DDYYYYYYYYWWWWWWYYYYYYYYDD..',
      '..DDDYYYYYYYWWWWWWYYYYYYYDDD..',
      '..DDDDDDDDDDDDDDDDDDDDDDDDDD..',
      '...DDDDDDDDDDDDDDDDDDDDDDDD...',
    ],
    legend: { R: RED, B: BLUE, Y: YELLOW, W: WHITE, D: DARK },
  },
  {
    name: 'Owl',
    // 34x32, 903 tiles, 7 colors
    rows: [
      '.....DD....................DD.....',
      '...DDDDDD................DDDDDD...',
      '...DDTTDD................DDTTDD...',
      '..DDTTTTTDD............DDTTTTTDD..',
      '..DDTTTTTDDDDDDDDDDDDDDDDTTTTTDD..',
      '...DDTTTTTTDDDDDDDDDDDDTTTTTTDD...',
      '....DTTTTTTTTTTTTTTTTTTTTTTTTD....',
      '....DDTTTTTTTTTTTTTTTTTTTTTTDD....',
      '...DDSTTTTTTTTTTTTTTTTTTTTTTSDD...',
      '.DDSSSTTTTTTTTTTTTTTTTTTTTTTSSSDD.',
      '.DDSSSTTTWWWWTTTTTTTTWWWWTTTSSSDD.',
      'DDSSSSTTWWWWWWTTTTTTWWWWWWTTSSSSDD',
      'DDSSSSTTWWYYWWTTTTTTWWYYWWTTSSSSDD',
      'DDSSSSTTWWYYWWTTTTTTWWYYWWTTSSSSDD',
      'DDSSSSTTWWWWWWTTOOTTWWWWWWTTSSSSDD',
      'DDSSSSTTTWWWWTTTOOTTTWWWWTTTSSSSDD',
      'DDSSSSTTTTTTTTTTOOTTTTTTTTTTSSSSDD',
      'DDSSSSTTTTTTTTTTOOTTTTTTTTTTSSSSDD',
      'DDSSSSTTTTTWWWWWWWWWWWWTTTTTSSSSDD',
      'DDSSSSTTTWWWWWWWWWWWWWWWWTTTSSSSDD',
      'DDSSSSTTTWWWDDWWWWDDWWWWWTTTSSSSDD',
      '.DDSSSTTWWWWDDWWWWDDWWWWWWTTSSSDD.',
      '.DDSSSTTWWWWWWWWWWWWWWWWWWTTSSSDD.',
      '..DDSSTTTWWWWWWWWWWWWWWWWTTTSSDD..',
      '..DDSSTTTWWWWWWWWWWWWWWWWTTTSSDD..',
      '...DDSTTTTTWWWWWWWWWWWWTTTTTSDD...',
      '...DDDTTTTTTTTTTTTTTTTTTTTTTDDD...',
      '.....DDTTTTTTTTTTTTTTTTTTTTDDD....',
      '.....DDDDDDDOOOODDDDOOOODDDDDD....',
      '......DDDDDDOOOODDDDOOOODDDDDDD...',
      '..DDGGGGGGGGGGGGGGGGGGGGGGGGGDDD..',
      '..DDGGGGGGGGGGGGGGGGGGGGGGGGGGDD..',
    ],
    legend: { Y: YELLOW, G: GREEN, O: ORANGE, W: WHITE, D: DARK, T: TAN, S: SLATE },
  },
];

export const PICTURE_COUNT = PICTURES.length;

export function picture(index: number): LibraryPicture {
  const found = PICTURES[index];
  if (!found) throw new Error(`picture: no picture at index ${index}`);
  return found;
}
